/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
typedef struct Tsym294834 Tsym294834;
typedef struct Tnode294802 Tnode294802;
typedef struct Tpass343014 Tpass343014;
typedef struct Tpasscontext343002 Tpasscontext343002;
typedef struct Trodreader334021 Trodreader334021;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef struct Tllstream284204 Tllstream284204;
typedef struct Tparsers319026 Tparsers319026;
typedef struct Tparser308202 Tparser308202;
typedef struct Tlexer287174 Tlexer287174;
typedef struct Tbaselexer285015 Tbaselexer285015;
typedef struct Tlineinfo193336 Tlineinfo193336;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Ttoken287170 Ttoken287170;
typedef struct Tident201010 Tident201010;
typedef struct Tidobj201004 Tidobj201004;
typedef struct Ttypeseq294836 Ttypeseq294836;
typedef struct TY294929 TY294929;
typedef struct Tstrtable294806 Tstrtable294806;
typedef struct Tsymseq294804 Tsymseq294804;
typedef struct Ttype294840 Ttype294840;
typedef struct Tloc294816 Tloc294816;
typedef struct Ropeobj180006 Ropeobj180006;
typedef struct Tlib294820 Tlib294820;
typedef struct TY136002 TY136002;
typedef struct Tnodeseq294796 Tnodeseq294796;
typedef struct TY294960 TY294960;
typedef struct TY396746 TY396746;
typedef struct TY334033 TY334033;
typedef struct Tindex334019 Tindex334019;
typedef struct Tiitable301142 Tiitable301142;
typedef struct Tiipairseq301140 Tiipairseq301140;
typedef struct Table334054 Table334054;
typedef struct Keyvaluepairseq334057 Keyvaluepairseq334057;
typedef struct Memfile332202 Memfile332202;
typedef struct Tinstantiation294824 Tinstantiation294824;
typedef struct Tlistentry148007 Tlistentry148007;
typedef struct TY294961 TY294961;
typedef struct Tiipair301138 Tiipair301138;
typedef struct Keyvaluepair334060 Keyvaluepair334060;
typedef N_NIMCALL_PTR(Tsym294834*, TY343069) (Tsym294834* m0, NI32 fileidx0);
typedef N_NIMCALL_PTR(Tnode294802*, TY343074) (Tsym294834* m0, NI32 fileidx0);
typedef N_NIMCALL_PTR(Tpasscontext343002*, Tpassopen343006) (Tsym294834* module0);
typedef N_NIMCALL_PTR(Tpasscontext343002*, Tpassopencached343008) (Tsym294834* module0, Trodreader334021* rd0);
typedef N_NIMCALL_PTR(Tnode294802*, Tpassprocess343012) (Tpasscontext343002* p0, Tnode294802* toplevelstmt0);
typedef N_NIMCALL_PTR(Tnode294802*, Tpassclose343010) (Tpasscontext343002* p0, Tnode294802* n0);
struct Tpass343014 {
Tpassopen343006 Field0;
Tpassopencached343008 Field1;
Tpassprocess343012 Field2;
Tpassclose343010 Field3;
};
typedef Tpass343014 TY343160[10];
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tpasscontext343002  {
  TNimObject Sup;
NIM_BOOL fromcache;
};
typedef NU8 Tparserkind319004;
struct  Tbaselexer285015  {
  TNimObject Sup;
NI bufpos;
NCSTRING buf;
NI buflen;
Tllstream284204* stream;
NI linenumber;
NI sentinel;
NI linestart;
};
typedef NU16 Tmsgkind193002;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (Tlineinfo193336 info0, Tmsgkind193002 msg0, NimStringDesc* arg0, void* ClEnv);
void* ClEnv;
} Terrorhandler287172;
struct  Tlexer287174  {
  Tbaselexer285015 Sup;
NI32 fileidx;
NI indentahead;
NI currlineindent;
NIM_BOOL strongspaces;
Terrorhandler287172 errorhandler;
};
typedef NU8 Ttoktype287016;
typedef NU8 Tnumericalbase287168;
struct  Ttoken287170  {
Ttoktype287016 toktype;
NI indent;
Tident201010* ident;
NI64 inumber;
NF fnumber;
Tnumericalbase287168 base;
NI8 strongspacea;
NI8 strongspaceb;
NimStringDesc* literal;
NI line;
NI col;
};
struct  Tparser308202  {
NI currind;
NIM_BOOL firsttok;
NIM_BOOL strongspaces;
Tlexer287174 lex;
Ttoken287170 tok;
NI inpragma;
NI insemistmtlist;
};
struct  Tparsers319026  {
Tparserkind319004 skin;
Tparser308202 parser;
};
typedef Tpasscontext343002* Tpasscontextarray343155[10];
struct  Tidobj201004  {
  TNimObject Sup;
NI id;
};
typedef NU8 Tsymkind294435;
struct  Tstrtable294806  {
NI counter;
Tsymseq294804* data;
};
typedef NU16 Tmagic294524;
struct  Tlineinfo193336  {
NI16 line;
NI16 col;
NI32 fileindex;
};
typedef NU32 Tsymflag294184Set;
typedef NU32 Toption171009Set;
typedef NU8 Tlockind294808;
typedef NU8 Tstorageloc294812;
typedef NU16 Tlocflag294810Set;
struct  Tloc294816  {
Tlockind294808 k;
Tstorageloc294812 s;
Tlocflag294810Set flags;
Ttype294840* t;
Ropeobj180006* r;
};
struct  Tsym294834  {
  Tidobj201004 Sup;
Tsymkind294435 kind;
union{
struct {Ttypeseq294836* typeinstcache;
} S1;
struct {TY294929* procinstcache;
Tsym294834* gcunsafetyreason;
} S2;
struct {TY294929* usedgenerics;
Tstrtable294806 tab;
} S3;
struct {Tsym294834* guard;
NI bitsize;
} S4;
} kindU;
Tmagic294524 magic;
Ttype294840* typ;
Tident201010* name;
Tlineinfo193336 info;
Tsym294834* owner;
Tsymflag294184Set flags;
Tnode294802* ast;
Toption171009Set options;
NI position;
NI offset;
Tloc294816 loc;
Tlib294820* annex;
Tnode294802* constraint;
};
typedef NU8 Filemode13009;
typedef NU8 Tsymflag294184;
typedef NU8 Tnodekind294020;
typedef NU16 Tnodeflag294427Set;
struct  Tnode294802  {
Ttype294840* typ;
Tlineinfo193336 info;
Tnodeflag294427Set flags;
Tnodekind294020 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym294834* sym;
} S4;
struct {Tident201010* ident;
} S5;
struct {Tnodeseq294796* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef NU8 Tllstreamkind284202;
struct  Tllstream284204  {
  TNimObject Sup;
Tllstreamkind284202 kind;
FILE* f;
NimStringDesc* s;
NI rd;
NI wr;
NI lineoffset;
};
typedef NU8 Ttypekind294244;
typedef NU8 Tcallingconvention294002;
typedef NU32 Ttypeflag294431Set;
struct  Ttype294840  {
  Tidobj201004 Sup;
Ttypekind294244 kind;
Tcallingconvention294002 callconv;
Ttypeflag294431Set flags;
Ttypeseq294836* sons;
Tnode294802* n;
Tsym294834* owner;
Tsym294834* sym;
Tsym294834* destructor;
Tsym294834* deepcopy;
Tsym294834* assignment;
TY294960* methods;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc294816 loc;
};
struct TY396746 {
Tnode294802* Field0;
Tnode294802* Field1;
};
typedef NU8 Treasonforrecompile334002;
struct  Tiitable301142  {
NI counter;
Tiipairseq301140* data;
};
struct  Tindex334019  {
NI lastidxkey;
NI lastidxval;
Tiitable301142 tab;
NimStringDesc* r;
NI offset;
};
struct  Table334054  {
Keyvaluepairseq334057* data;
NI counter;
};
struct  Memfile332202  {
void* mem;
NI size;
int handle;
};
struct  Trodreader334021  {
  TNimObject Sup;
NI pos;
NCSTRING s;
Toption171009Set options;
Treasonforrecompile334002 reason;
TY334033* moddeps;
TY334033* files;
NI dataidx;
NI convertersidx;
NI initidx;
NI interfidx;
NI compilerprocsidx;
NI methodsidx;
NimStringDesc* filename;
Tindex334019 index;
Tindex334019 imports;
NI readerindex;
NI line;
NI moduleid;
Table334054 syms;
Memfile332202 memfile;
Tsymseq294804* methods;
NimStringDesc* origfile;
NIM_BOOL inviewmode;
};
struct  Tident201010  {
  Tidobj201004 Sup;
NimStringDesc* s;
Tident201010* next;
NI h;
};
struct  Ropeobj180006  {
  TNimObject Sup;
Ropeobj180006* left;
Ropeobj180006* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry148007  {
  TNimObject Sup;
Tlistentry148007* prev;
Tlistentry148007* next;
};
typedef NU8 Tlibkind294818;
struct  Tlib294820  {
  Tlistentry148007 Sup;
Tlibkind294818 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj180006* name;
Tnode294802* path;
};
struct TY294961 {
NI Field0;
Tsym294834* Field1;
};
struct  Tiipair301138  {
NI key;
NI val;
};
struct Keyvaluepair334060 {
NI Field0;
NI Field1;
Tsym294834* Field2;
};
struct  Tinstantiation294824  {
Tsym294834* sym;
Ttypeseq294836* concretetypes;
NI compilesid;
};
struct TY136002 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct Ttypeseq294836 {
  TGenericSeq Sup;
  Ttype294840* data[SEQ_DECL_SIZE];
};
struct TY294929 {
  TGenericSeq Sup;
  Tinstantiation294824* data[SEQ_DECL_SIZE];
};
struct Tsymseq294804 {
  TGenericSeq Sup;
  Tsym294834* data[SEQ_DECL_SIZE];
};
struct Tnodeseq294796 {
  TGenericSeq Sup;
  Tnode294802* data[SEQ_DECL_SIZE];
};
struct TY294960 {
  TGenericSeq Sup;
  TY294961 data[SEQ_DECL_SIZE];
};
struct TY334033 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
struct Tiipairseq301140 {
  TGenericSeq Sup;
  Tiipair301138 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq334057 {
  TGenericSeq Sup;
  Keyvaluepair334060 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, objectInit)(void* dest0, TNimType* typ0);
N_NIMCALL(void, openpasses_343233_2355241294)(Tpasscontext343002** a0, Tsym294834* module0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(NimStringDesc*, tofullpathconsiderdirty_194401_155036129)(NI32 fileidx0);
N_NIMCALL(Tllstream284204*, llstreamopen_284242_597494479)(NimStringDesc* filename0, Filemode13009 mode0);
N_NIMCALL(void, rawmessage_196612_155036129)(Tmsgkind193002 msg0, NimStringDesc* arg0);
N_NIMCALL(void, openparsers_319032_4241778752)(Tparsers319026* p0, NI32 fileidx0, Tllstream284204* inputstream0);
N_NIMCALL(void, processimplicits_343465_2355241294)(TY136002* implicits0, Tnodekind294020 nodekind0, Tpasscontext343002** a0);
N_NIMCALL(Tnode294802*, newnodei_296197_850551059)(Tnodekind294020 kind0, Tlineinfo193336 info0);
N_NIMCALL(Tnode294802*, newstrnode_295678_850551059)(Tnodekind294020 kind0, NimStringDesc* strval0);
N_NIMCALL(void, addson_296807_850551059)(Tnode294802* father0, Tnode294802* son0);
N_NIMCALL(NIM_BOOL, processtoplevelstmt_343346_2355241294)(Tnode294802* n0, Tpasscontext343002** a0);
N_NIMCALL(Tnode294802*, parsetoplevelstmt_319046_4241778752)(Tparsers319026* p0);
N_NIMCALL(void, add_295136_850551059)(Tnode294802* father0, Tnode294802* son0);
N_NIMCALL(void, closeparsers_319038_4241778752)(Tparsers319026* p0);
N_NIMCALL(void, closepasses_343312_2355241294)(Tpasscontext343002** a0);
N_NIMCALL(void, idsynchronizationpoint_293420_644355110)(NI idrange0);
N_NIMCALL(void, openpassescached_343266_2355241294)(Tpasscontext343002** a0, Tsym294834* module0, Trodreader334021* rd0);
N_NIMCALL(Tnode294802*, loadinitsection_336822_1724185294)(Trodreader334021* r0);
N_NIMCALL(NI, sonslen_297351_850551059)(Tnode294802* n0);
N_NIMCALL(void, processtoplevelstmtcached_343389_2355241294)(Tnode294802* n0, Tpasscontext343002** a0);
N_NIMCALL(void, closepassescached_343423_2355241294)(Tpasscontext343002** a0);
N_NIMCALL(void, carrypass_343179_2355241294)(Tpass343014 p0, Tsym294834* module0, TY396746 m0, TY396746* Result);
TY343069 gimportmodule_343073_2355241294;
TY343074 gincludefile_343078_2355241294;
TY343160 gpasses_343161_2355241294;
NI gpasseslen_343162_2355241294;
extern TNimType NTI3608; /* RootObj */
TNimType NTI343002; /* TPassContext */
extern TNimType NTI130; /* bool */
extern TNimType NTI319026; /* TParsers */
extern Tlineinfo193336 gcmdlineinfo_194037_155036129;
extern TY136002* implicitimports_171252_2607990831;
extern TY136002* implicitincludes_171270_2607990831;

N_NIMCALL(void, openpasses_343233_2355241294)(Tpasscontext343002** a0, Tsym294834* module0) {
	{
		NI i_343249_2355241294;
		NI HEX3Atmp_343258_2355241294;
		NI res_343261_2355241294;
		i_343249_2355241294 = (NI)0;
		HEX3Atmp_343258_2355241294 = (NI)0;
		HEX3Atmp_343258_2355241294 = (NI)(gpasseslen_343162_2355241294 - ((NI) 1));
		res_343261_2355241294 = ((NI) 0);
		{
			while (1) {
				if (!(res_343261_2355241294 <= HEX3Atmp_343258_2355241294)) goto LA3;
				i_343249_2355241294 = res_343261_2355241294;
				{
					if (!!(gpasses_343161_2355241294[(i_343249_2355241294)- 0].Field0 == 0)) goto LA6;
					unsureAsgnRef((void**) (&a0[(i_343249_2355241294)- 0]), gpasses_343161_2355241294[(i_343249_2355241294)- 0].Field0(module0));
				}
				goto LA4;
				LA6: ;
				{
					unsureAsgnRef((void**) (&a0[(i_343249_2355241294)- 0]), NIM_NIL);
				}
				LA4: ;
				res_343261_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(NIM_BOOL, processtoplevelstmt_343346_2355241294)(Tnode294802* n0, Tpasscontext343002** a0) {
	NIM_BOOL result0;
	Tnode294802* m0;
{	result0 = (NIM_BOOL)0;
	m0 = n0;
	{
		NI i_343364_2355241294;
		NI HEX3Atmp_343381_2355241294;
		NI res_343384_2355241294;
		i_343364_2355241294 = (NI)0;
		HEX3Atmp_343381_2355241294 = (NI)0;
		HEX3Atmp_343381_2355241294 = (NI)(gpasseslen_343162_2355241294 - ((NI) 1));
		res_343384_2355241294 = ((NI) 0);
		{
			while (1) {
				if (!(res_343384_2355241294 <= HEX3Atmp_343381_2355241294)) goto LA3;
				i_343364_2355241294 = res_343384_2355241294;
				{
					if (!!(gpasses_343161_2355241294[(i_343364_2355241294)- 0].Field2 == 0)) goto LA6;
					m0 = gpasses_343161_2355241294[(i_343364_2355241294)- 0].Field2(a0[(i_343364_2355241294)- 0], m0);
					{
						if (!m0 == 0) goto LA10;
						result0 = NIM_FALSE;
						goto BeforeRet;
					}
					LA10: ;
				}
				LA6: ;
				res_343384_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
	result0 = NIM_TRUE;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, processimplicits_343465_2355241294)(TY136002* implicits0, Tnodekind294020 nodekind0, Tpasscontext343002** a0) {
	{
		NimStringDesc* module_343480_2355241294;
		NI i_343487_2355241294;
		NI L_343489_2355241294;
		module_343480_2355241294 = (NimStringDesc*)0;
		i_343487_2355241294 = ((NI) 0);
		L_343489_2355241294 = (implicits0 ? implicits0->Sup.len : 0);
		{
			while (1) {
				Tnode294802* importstmt0;
				Tnode294802* str0;
				if (!(i_343487_2355241294 < L_343489_2355241294)) goto LA3;
				module_343480_2355241294 = implicits0->data[i_343487_2355241294];
				importstmt0 = newnodei_296197_850551059(nodekind0, gcmdlineinfo_194037_155036129);
				str0 = newstrnode_295678_850551059(((Tnodekind294020) 20), module_343480_2355241294);
				(*str0).info = gcmdlineinfo_194037_155036129;
				addson_296807_850551059(importstmt0, str0);
				{
					NIM_BOOL LOC6;
					LOC6 = (NIM_BOOL)0;
					LOC6 = processtoplevelstmt_343346_2355241294(importstmt0, a0);
					if (!!(LOC6)) goto LA7;
					goto LA1;
				}
				LA7: ;
				i_343487_2355241294 += ((NI) 1);
			} LA3: ;
		}
	} LA1: ;
}

N_NIMCALL(void, closepasses_343312_2355241294)(Tpasscontext343002** a0) {
	Tnode294802* m0;
	m0 = NIM_NIL;
	{
		NI i_343328_2355241294;
		NI HEX3Atmp_343338_2355241294;
		NI res_343341_2355241294;
		i_343328_2355241294 = (NI)0;
		HEX3Atmp_343338_2355241294 = (NI)0;
		HEX3Atmp_343338_2355241294 = (NI)(gpasseslen_343162_2355241294 - ((NI) 1));
		res_343341_2355241294 = ((NI) 0);
		{
			while (1) {
				if (!(res_343341_2355241294 <= HEX3Atmp_343338_2355241294)) goto LA3;
				i_343328_2355241294 = res_343341_2355241294;
				{
					if (!!(gpasses_343161_2355241294[(i_343328_2355241294)- 0].Field3 == 0)) goto LA6;
					m0 = gpasses_343161_2355241294[(i_343328_2355241294)- 0].Field3(a0[(i_343328_2355241294)- 0], m0);
				}
				LA6: ;
				unsureAsgnRef((void**) (&a0[(i_343328_2355241294)- 0]), NIM_NIL);
				res_343341_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, openpassescached_343266_2355241294)(Tpasscontext343002** a0, Tsym294834* module0, Trodreader334021* rd0) {
	{
		NI i_343283_2355241294;
		NI HEX3Atmp_343304_2355241294;
		NI res_343307_2355241294;
		i_343283_2355241294 = (NI)0;
		HEX3Atmp_343304_2355241294 = (NI)0;
		HEX3Atmp_343304_2355241294 = (NI)(gpasseslen_343162_2355241294 - ((NI) 1));
		res_343307_2355241294 = ((NI) 0);
		{
			while (1) {
				if (!(res_343307_2355241294 <= HEX3Atmp_343304_2355241294)) goto LA3;
				i_343283_2355241294 = res_343307_2355241294;
				{
					if (!!(gpasses_343161_2355241294[(i_343283_2355241294)- 0].Field1 == 0)) goto LA6;
					unsureAsgnRef((void**) (&a0[(i_343283_2355241294)- 0]), gpasses_343161_2355241294[(i_343283_2355241294)- 0].Field1(module0, rd0));
					{
						if (!!((a0[(i_343283_2355241294)- 0] == NIM_NIL))) goto LA10;
						(*a0[(i_343283_2355241294)- 0]).fromcache = NIM_TRUE;
					}
					LA10: ;
				}
				goto LA4;
				LA6: ;
				{
					unsureAsgnRef((void**) (&a0[(i_343283_2355241294)- 0]), NIM_NIL);
				}
				LA4: ;
				res_343307_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, processtoplevelstmtcached_343389_2355241294)(Tnode294802* n0, Tpasscontext343002** a0) {
	Tnode294802* m0;
	m0 = n0;
	{
		NI i_343406_2355241294;
		NI HEX3Atmp_343415_2355241294;
		NI res_343418_2355241294;
		i_343406_2355241294 = (NI)0;
		HEX3Atmp_343415_2355241294 = (NI)0;
		HEX3Atmp_343415_2355241294 = (NI)(gpasseslen_343162_2355241294 - ((NI) 1));
		res_343418_2355241294 = ((NI) 0);
		{
			while (1) {
				if (!(res_343418_2355241294 <= HEX3Atmp_343415_2355241294)) goto LA3;
				i_343406_2355241294 = res_343418_2355241294;
				{
					if (!!(gpasses_343161_2355241294[(i_343406_2355241294)- 0].Field1 == 0)) goto LA6;
					m0 = gpasses_343161_2355241294[(i_343406_2355241294)- 0].Field2(a0[(i_343406_2355241294)- 0], m0);
				}
				LA6: ;
				res_343418_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, closepassescached_343423_2355241294)(Tpasscontext343002** a0) {
	Tnode294802* m0;
	m0 = NIM_NIL;
	{
		NI i_343439_2355241294;
		NI HEX3Atmp_343456_2355241294;
		NI res_343459_2355241294;
		i_343439_2355241294 = (NI)0;
		HEX3Atmp_343456_2355241294 = (NI)0;
		HEX3Atmp_343456_2355241294 = (NI)(gpasseslen_343162_2355241294 - ((NI) 1));
		res_343459_2355241294 = ((NI) 0);
		{
			while (1) {
				if (!(res_343459_2355241294 <= HEX3Atmp_343456_2355241294)) goto LA3;
				i_343439_2355241294 = res_343459_2355241294;
				{
					NIM_BOOL LOC6;
					LOC6 = (NIM_BOOL)0;
					LOC6 = !(gpasses_343161_2355241294[(i_343439_2355241294)- 0].Field1 == 0);
					if (!(LOC6)) goto LA7;
					LOC6 = !(gpasses_343161_2355241294[(i_343439_2355241294)- 0].Field3 == 0);
					LA7: ;
					if (!LOC6) goto LA8;
					m0 = gpasses_343161_2355241294[(i_343439_2355241294)- 0].Field3(a0[(i_343439_2355241294)- 0], m0);
				}
				LA8: ;
				unsureAsgnRef((void**) (&a0[(i_343439_2355241294)- 0]), NIM_NIL);
				res_343459_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(NIM_BOOL, processmodule_343490_2355241294)(Tsym294834* module0, Tllstream284204* stream0, Trodreader334021* rd0) {
	NIM_BOOL result0;
	Tparsers319026 p0;
	Tpasscontextarray343155 a0;
	Tllstream284204* s0;
	NI32 fileidx0;
{	result0 = (NIM_BOOL)0;
	memset((void*)(&p0), 0, sizeof(p0));
	objectInit((&p0), (&NTI319026));
	memset((void*)a0, 0, sizeof(a0));
	s0 = (Tllstream284204*)0;
	fileidx0 = ((NI32) ((*module0).position));
	{
		if (!(rd0 == NIM_NIL)) goto LA3;
		openpasses_343233_2355241294(a0, module0);
		{
			NimStringDesc* filename0;
			if (!(stream0 == NIM_NIL)) goto LA7;
			filename0 = tofullpathconsiderdirty_194401_155036129(fileidx0);
			s0 = llstreamopen_284242_597494479(filename0, ((Filemode13009) 0));
			{
				if (!(s0 == NIM_NIL)) goto LA11;
				rawmessage_196612_155036129(((Tmsgkind193002) 3), filename0);
				result0 = NIM_FALSE;
				goto BeforeRet;
			}
			LA11: ;
		}
		goto LA5;
		LA7: ;
		{
			s0 = stream0;
		}
		LA5: ;
		{
			while (1) {
				openparsers_319032_4241778752((&p0), fileidx0, s0);
				{
					if (!!((((*module0).flags &(1U<<((NU)(((Tsymflag294184) 13))&31U)))!=0))) goto LA18;
					processimplicits_343465_2355241294(implicitimports_171252_2607990831, ((Tnodekind294020) 116), a0);
					processimplicits_343465_2355241294(implicitincludes_171270_2607990831, ((Tnodekind294020) 121), a0);
				}
				LA18: ;
				{
					while (1) {
						Tnode294802* n_343556_2355241294;
						n_343556_2355241294 = parsetoplevelstmt_319046_4241778752((&p0));
						{
							if (!((*n_343556_2355241294).kind == ((Tnodekind294020) 1))) goto LA24;
							goto LA20;
						}
						LA24: ;
						{
							Tnode294802* sl0;
							NIM_BOOL LOC36;
							if (!(((*module0).flags &(1U<<((NU)(((Tsymflag294184) 8))&31U)))!=0)) goto LA28;
							sl0 = newnodei_296197_850551059(((Tnodekind294020) 115), (*n_343556_2355241294).info);
							add_295136_850551059(sl0, n_343556_2355241294);
							{
								while (1) {
									Tnode294802* n0;
									n0 = parsetoplevelstmt_319046_4241778752((&p0));
									{
										if (!((*n0).kind == ((Tnodekind294020) 1))) goto LA34;
										goto LA30;
									}
									LA34: ;
									add_295136_850551059(sl0, n0);
								}
							} LA30: ;
							LOC36 = (NIM_BOOL)0;
							LOC36 = processtoplevelstmt_343346_2355241294(sl0, a0);
							goto LA20;
						}
						goto LA26;
						LA28: ;
						{
							NIM_BOOL LOC38;
							LOC38 = (NIM_BOOL)0;
							LOC38 = processtoplevelstmt_343346_2355241294(n_343556_2355241294, a0);
							if (!!(LOC38)) goto LA39;
							goto LA20;
						}
						goto LA26;
						LA39: ;
						LA26: ;
					}
				} LA20: ;
				closeparsers_319038_4241778752((&p0));
				{
					if (!!(((*s0).kind == ((Tllstreamkind284202) 3)))) goto LA43;
					goto LA14;
				}
				LA43: ;
			}
		} LA14: ;
		closepasses_343312_2355241294(a0);
		idsynchronizationpoint_293420_644355110(((NI) 1000));
	}
	goto LA1;
	LA3: ;
	{
		Tnode294802* n0;
		openpassescached_343266_2355241294(a0, module0, rd0);
		n0 = loadinitsection_336822_1724185294(rd0);
		{
			NI i_343618_2355241294;
			NI HEX3Atmp_343630_2355241294;
			NI LOC47;
			NI res_343633_2355241294;
			i_343618_2355241294 = (NI)0;
			HEX3Atmp_343630_2355241294 = (NI)0;
			LOC47 = (NI)0;
			LOC47 = sonslen_297351_850551059(n0);
			HEX3Atmp_343630_2355241294 = (NI)(LOC47 - ((NI) 1));
			res_343633_2355241294 = ((NI) 0);
			{
				while (1) {
					if (!(res_343633_2355241294 <= HEX3Atmp_343630_2355241294)) goto LA49;
					i_343618_2355241294 = res_343633_2355241294;
					processtoplevelstmtcached_343389_2355241294((*n0).kindU.S6.sons->data[i_343618_2355241294], a0);
					res_343633_2355241294 += ((NI) 1);
				} LA49: ;
			}
		}
		closepassescached_343423_2355241294(a0);
	}
	LA1: ;
	result0 = NIM_TRUE;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, registerpass_343167_2355241294)(Tpass343014 p0) {
	gpasses_343161_2355241294[(gpasseslen_343162_2355241294)- 0] = p0;
	gpasseslen_343162_2355241294 += ((NI) 1);
}

N_NIMCALL(void, clearpasses_343165_2355241294)(void) {
	gpasseslen_343162_2355241294 = ((NI) 0);
}

N_NIMCALL(NIM_BOOL, astneeded_343089_2355241294)(Tsym294834* s0) {
	NIM_BOOL result0;
	result0 = (NIM_BOOL)0;
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		LOC3 = (NIM_BOOL)0;
		LOC4 = (NIM_BOOL)0;
		LOC5 = (NIM_BOOL)0;
		LOC5 = ((12288 &(1U<<((NU)((*s0).kind)&31U)))!=0);
		if (!(LOC5)) goto LA6;
		LOC5 = ((8454144 & (*s0).flags) == 0);
		LA6: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA7;
		LOC4 = !(((*(*s0).typ).callconv == ((Tcallingconvention294002) 5)));
		LA7: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA8;
		LOC3 = ((*(*(*s0).ast).kindU.S6.sons->data[((NI) 2)]).kind == ((Tnodekind294020) 1));
		LA8: ;
		if (!LOC3) goto LA9;
		result0 = NIM_FALSE;
	}
	goto LA1;
	LA9: ;
	{
		result0 = NIM_TRUE;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void, carrypass_343179_2355241294)(Tpass343014 p0, Tsym294834* module0, TY396746 m0, TY396746* Result) {
	Tpasscontext343002* c0;
	c0 = p0.Field0(module0);
	unsureAsgnRef((void**) (&(*Result).Field0), p0.Field2(c0, m0.Field0));
	{
		if (!!((p0.Field3 == NIM_NIL))) goto LA3;
		unsureAsgnRef((void**) (&(*Result).Field1), p0.Field3(c0, m0.Field1));
	}
	goto LA1;
	LA3: ;
	{
		unsureAsgnRef((void**) (&(*Result).Field1), m0.Field1);
	}
	LA1: ;
}

N_NIMCALL(void, carrypasses_343196_2355241294)(Tnode294802* nodes0, Tsym294834* module0, Tpass343014* passes0, NI passes0Len0) {
	TY396746 passdata0;
	memset((void*)(&passdata0), 0, sizeof(passdata0));
	passdata0.Field0 = nodes0;
	{
		Tpass343014 pass_343227_2355241294;
		NI i_343232_2355241294;
		memset((void*)(&pass_343227_2355241294), 0, sizeof(pass_343227_2355241294));
		i_343232_2355241294 = ((NI) 0);
		{
			while (1) {
				TY396746 LOC4;
				if (!(i_343232_2355241294 < passes0Len0)) goto LA3;
				pass_343227_2355241294 = passes0[i_343232_2355241294];
				memset((void*)(&LOC4), 0, sizeof(LOC4));
				carrypass_343179_2355241294(pass_343227_2355241294, module0, passdata0, (&LOC4));
				passdata0.Field0 = LOC4.Field0;
				passdata0.Field1 = LOC4.Field1;
				i_343232_2355241294 += ((NI) 1);
			} LA3: ;
		}
	}
}
NIM_EXTERNC N_NOINLINE(void, compiler_passesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, compiler_passesDatInit000)(void) {
static TNimNode T2355241294_0[1];
NTI343002.size = sizeof(Tpasscontext343002);
NTI343002.kind = 17;
NTI343002.base = (&NTI3608);
NTI343002.flags = 1;
T2355241294_0[0].kind = 1;
T2355241294_0[0].offset = offsetof(Tpasscontext343002, fromcache);
T2355241294_0[0].typ = (&NTI130);
T2355241294_0[0].name = "fromCache";
NTI343002.node = &T2355241294_0[0];
}

