/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct ttable167560 ttable167560;
typedef struct tkeyvaluepairseq167563 tkeyvaluepairseq167563;
typedef struct tkeyvaluepair167566 tkeyvaluepair167566;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell41888 tcell41888;
typedef struct tcellseq41904 tcellseq41904;
typedef struct tgcheap43816 tgcheap43816;
typedef struct tcellset41900 tcellset41900;
typedef struct tpagedesc41896 tpagedesc41896;
typedef struct tmemregion24210 tmemregion24210;
typedef struct tsmallchunk23438 tsmallchunk23438;
typedef struct tllchunk24204 tllchunk24204;
typedef struct tbigchunk23440 tbigchunk23440;
typedef struct tintset23415 tintset23415;
typedef struct ttrunk23411 ttrunk23411;
typedef struct tavlnode24208 tavlnode24208;
typedef struct tgcstat43814 tgcstat43814;
typedef struct tbasechunk23436 tbasechunk23436;
typedef struct tfreecell23428 tfreecell23428;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tkeyvaluepair167566 {
NU8 Field0;
NimStringDesc* Field1;
NI32 Field2;
};
struct  ttable167560  {
tkeyvaluepairseq167563* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41888  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41904  {
NI Len;
NI Cap;
tcell41888** D;
};
struct  tcellset41900  {
NI Counter;
NI Max;
tpagedesc41896* Head;
tpagedesc41896** Data;
};
typedef tsmallchunk23438* TY24222[512];
typedef ttrunk23411* ttrunkbuckets23413[256];
struct  tintset23415  {
ttrunkbuckets23413 Data;
};
struct  tmemregion24210  {
NI Minlargeobj;
NI Maxlargeobj;
TY24222 Freesmallchunks;
tllchunk24204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk23440* Freechunkslist;
tintset23415 Chunkstarts;
tavlnode24208* Root;
tavlnode24208* Deleted;
tavlnode24208* Last;
tavlnode24208* Freeavlnodes;
};
struct  tgcstat43814  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43816  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41904 Zct;
tcellseq41904 Decstack;
tcellset41900 Cycleroots;
tcellseq41904 Tempstack;
NI Recgclock;
tmemregion24210 Region;
tgcstat43814 Stat;
};
typedef NI TY23418[16];
struct  tpagedesc41896  {
tpagedesc41896* Next;
NI Key;
TY23418 Bits;
};
struct  tbasechunk23436  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk23438  {
  tbasechunk23436 Sup;
tsmallchunk23438* Next;
tsmallchunk23438* Prev;
tfreecell23428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk24204  {
NI Size;
NI Acc;
tllchunk24204* Next;
};
struct  tbigchunk23440  {
  tbasechunk23436 Sup;
tbigchunk23440* Next;
tbigchunk23440* Prev;
NI Align;
NF Data;
};
struct  ttrunk23411  {
ttrunk23411* Next;
NI Key;
TY23418 Bits;
};
typedef tavlnode24208* TY24214[2];
struct  tavlnode24208  {
TY24214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell23428  {
tfreecell23428* Next;
NI Zerofield;
};
struct tkeyvaluepairseq167563 {
  TGenericSeq Sup;
  tkeyvaluepair167566 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_141414)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_80621)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_141606)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, ispoweroftwo_134278)(NI x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP896)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, rawget_167744)(ttable167560 t_167751, NimStringDesc* key_167754);
N_NIMCALL(NI, hash_120827)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, enlarge_167886)(ttable167560* t_167895);
N_NIMCALL(void, rawinsert_167956)(ttable167560* t_167965, tkeyvaluepairseq167563** data_167973, NimStringDesc* key_167977, NI32 val_167979);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41888*, usrtocell_45243)(void* usr);
static N_INLINE(void, rtladdzct_46802)(tcell41888* c);
N_NOINLINE(void, addzct_45218)(tcellseq41904* s, tcell41888* c);
STRING_LITERAL(TMP459, "length > counter ", 17);
STRING_LITERAL(TMP891, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_13238;
TNimType NTI167566; /* TKeyValuePair */
TNimType NTI141010; /* TSlotEnum */
extern TNimType NTI143; /* string */
extern TNimType NTI112; /* int32 */
TNimType NTI167563; /* TKeyValuePairSeq */
TNimType NTI167560; /* TTable */
extern TNimType NTI106; /* int */
extern tgcheap43816 gch_43844;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_141414)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP460;
	NI TMP461;
	NI TMP462;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(108, "tables.nim");
	{
		nimln(108, "tables.nim");
		nimln(108, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(108, "tables.nim");
		failedassertimpl_80621(((NimStringDesc*) &TMP459));
	}
	LA3: ;
	nimln(109, "tables.nim");
	nimln(109, "tables.nim");
	LOC5 = 0;
	nimln(109, "tables.nim");
	nimln(109, "tables.nim");
	TMP460 = mulInt(length, 2);
	nimln(109, "tables.nim");
	TMP461 = mulInt(counter, 3);
	LOC5 = ((NI32)(TMP460) < (NI32)(TMP461));
	if (LOC5) goto LA6;
	nimln(109, "tables.nim");
	nimln(109, "tables.nim");
	TMP462 = subInt(length, counter);
	LOC5 = ((NI32)(TMP462) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_141606)(NI h, NI maxhash) {
	NI result;
	NI TMP463;
	NI TMP464;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(112, "tables.nim");
	nimln(112, "tables.nim");
	nimln(112, "tables.nim");
	nimln(112, "tables.nim");
	TMP463 = mulInt(5, h);
	TMP464 = addInt((NI32)(TMP463), 1);
	result = (NI)((NI32)(TMP464) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP896)(void* p, NI op) {
	tkeyvaluepairseq167563* a;
	NI LOC1;
	a = (tkeyvaluepairseq167563*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_167552)(NI initialsize_167557, ttable167560* Result) {
	nimfr("initTable", "tables.nim")
	nimln(209, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(209, "tables.nim");
		nimln(209, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_134278(initialsize_167557);
		if (!!(LOC3)) goto LA4;
		nimln(209, "tables.nim");
		failedassertimpl_80621(((NimStringDesc*) &TMP891));
	}
	LA4: ;
	nimln(210, "tables.nim");
	(*Result).Counter = 0;
	nimln(211, "tables.nim");
	unsureAsgnRef((void**) &(*Result).Data, (tkeyvaluepairseq167563*) newSeq((&NTI167563), initialsize_167557));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawget_167744)(ttable167560 t_167751, NimStringDesc* key_167754) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(115, "tables.nim");
	nimln(115, "tables.nim");
	nimln(115, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_120827(key_167754);
	nimln(115, "tables.nim");
	h = (NI)(LOC1 & (t_167751.Data->Sup.len-1));
	nimln(116, "tables.nim");
	while (1) {
		nimln(116, "tables.nim");
		nimln(116, "tables.nim");
		if ((NU)(h) >= (NU)(t_167751.Data->Sup.len)) raiseIndexError();
		if (!!((t_167751.Data->data[h].Field0 == ((NU8) 0)))) goto LA2;
		nimln(117, "tables.nim");
		{
			NIM_BOOL LOC5;
			nimln(117, "tables.nim");
			LOC5 = 0;
			nimln(117, "tables.nim");
			if ((NU)(h) >= (NU)(t_167751.Data->Sup.len)) raiseIndexError();
			LOC5 = eqStrings(t_167751.Data->data[h].Field1, key_167754);
			if (!(LOC5)) goto LA6;
			nimln(117, "tables.nim");
			if ((NU)(h) >= (NU)(t_167751.Data->Sup.len)) raiseIndexError();
			LOC5 = (t_167751.Data->data[h].Field0 == ((NU8) 1));
			LA6: ;
			if (!LOC5) goto LA7;
			nimln(118, "tables.nim");
			nimln(118, "tables.nim");
			result = h;
			goto BeforeRet;
		}
		LA7: ;
		nimln(119, "tables.nim");
		nimln(119, "tables.nim");
		h = nexttry_141606(h, (t_167751.Data->Sup.len-1));
	} LA2: ;
	nimln(120, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_167730)(ttable167560 t_167737, NimStringDesc* key_167740) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(150, "tables.nim");
	nimln(150, "tables.nim");
	nimln(150, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_167744(t_167737, key_167740);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NI32, HEX5BHEX5D_167781)(ttable167560 t_167788, NimStringDesc* key_167791) {
	NI32 result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(138, "tables.nim");
	index = rawget_167744(t_167788, key_167791);
	nimln(139, "tables.nim");
	{
		nimln(139, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(139, "tables.nim");
		if ((NU)(index) >= (NU)(t_167788.Data->Sup.len)) raiseIndexError();
		result = t_167788.Data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(tcell41888*, usrtocell_45243)(void* usr) {
	tcell41888* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41888*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell41888))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46802)(tcell41888* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_45218(&gch_43844.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41888* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_45243(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46802(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_167956)(ttable167560* t_167965, tkeyvaluepairseq167563** data_167973, NimStringDesc* key_167977, NI32 val_167979) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC3;
	nimfr("rawInsert", "tables.nim")
	nimln(123, "tables.nim");
	nimln(123, "tables.nim");
	nimln(123, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_120827(key_167977);
	nimln(123, "tables.nim");
	h = (NI)(LOC1 & ((*data_167973)->Sup.len-1));
	nimln(124, "tables.nim");
	while (1) {
		nimln(124, "tables.nim");
		if ((NU)(h) >= (NU)((*data_167973)->Sup.len)) raiseIndexError();
		if (!((*data_167973)->data[h].Field0 == ((NU8) 1))) goto LA2;
		nimln(125, "tables.nim");
		nimln(125, "tables.nim");
		h = nexttry_141606(h, ((*data_167973)->Sup.len-1));
	} LA2: ;
	nimln(126, "tables.nim");
	if ((NU)(h) >= (NU)((*data_167973)->Sup.len)) raiseIndexError();
	LOC3 = 0;
	LOC3 = (*data_167973)->data[h].Field1; (*data_167973)->data[h].Field1 = copyStringRC1(key_167977);
	if (LOC3) nimGCunrefNoCycle(LOC3);
	nimln(127, "tables.nim");
	if ((NU)(h) >= (NU)((*data_167973)->Sup.len)) raiseIndexError();
	(*data_167973)->data[h].Field2 = val_167979;
	nimln(128, "tables.nim");
	if ((NU)(h) >= (NU)((*data_167973)->Sup.len)) raiseIndexError();
	(*data_167973)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_167886)(ttable167560* t_167895) {
	tkeyvaluepairseq167563* n;
	NI TMP909;
	NI i_167941;
	NI HEX3Atmp_168011;
	NI res_168013;
	tkeyvaluepairseq167563* LOC6;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(158, "tables.nim");
	nimln(158, "tables.nim");
	nimln(158, "tables.nim");
	TMP909 = mulInt((*t_167895).Data->Sup.len, 2);
	n = (tkeyvaluepairseq167563*) newSeq((&NTI167563), (NI32)(TMP909));
	i_167941 = 0;
	HEX3Atmp_168011 = 0;
	nimln(159, "tables.nim");
	nimln(159, "tables.nim");
	HEX3Atmp_168011 = ((*t_167895).Data->Sup.len-1);
	nimln(1451, "system.nim");
	res_168013 = 0;
	nimln(1452, "system.nim");
	while (1) {
		nimln(1452, "system.nim");
		if (!(res_168013 <= HEX3Atmp_168011)) goto LA1;
		nimln(1451, "system.nim");
		i_167941 = res_168013;
		nimln(160, "tables.nim");
		{
			nimln(160, "tables.nim");
			if ((NU)(i_167941) >= (NU)((*t_167895).Data->Sup.len)) raiseIndexError();
			if (!((*t_167895).Data->data[i_167941].Field0 == ((NU8) 1))) goto LA4;
			nimln(160, "tables.nim");
			if ((NU)(i_167941) >= (NU)((*t_167895).Data->Sup.len)) raiseIndexError();
			if ((NU)(i_167941) >= (NU)((*t_167895).Data->Sup.len)) raiseIndexError();
			rawinsert_167956(t_167895, &n, (*t_167895).Data->data[i_167941].Field1, (*t_167895).Data->data[i_167941].Field2);
		}
		LA4: ;
		nimln(1454, "system.nim");
		res_168013 = addInt(res_168013, 1);
	} LA1: ;
	nimln(161, "tables.nim");
	LOC6 = 0;
	LOC6 = (*t_167895).Data;
	unsureAsgnRef((void**) &(*t_167895).Data, n);
	n = LOC6;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_167841)(ttable167560* t_167850, NimStringDesc* key_167854, NI32 val_167856) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(169, "tables.nim");
	index = rawget_167744((*t_167850), key_167854);
	nimln(170, "tables.nim");
	{
		nimln(170, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(171, "tables.nim");
		if ((NU)(index) >= (NU)((*t_167850).Data->Sup.len)) raiseIndexError();
		(*t_167850).Data->data[index].Field2 = val_167856;
	}
	goto LA1;
	LA3: ;
	{
		nimln(164, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(164, "tables.nim");
			nimln(164, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_141414((*t_167850).Data->Sup.len, (*t_167850).Counter);
			if (!LOC8) goto LA9;
			nimln(164, "tables.nim");
			enlarge_167886(t_167850);
		}
		LA9: ;
		nimln(165, "tables.nim");
		rawinsert_167956(t_167850, &(*t_167850).Data, key_167854, val_167856);
		nimln(166, "tables.nim");
		(*t_167850).Counter = addInt((*t_167850).Counter, 1);
	}
	LA1: ;
	popFrame();
}
N_NOINLINE(void, stdlibtablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

N_NOINLINE(void, stdlibtablesDatInit)(void) {
static TNimNode* TMP892[3];
static TNimNode* TMP893[3];
NI TMP895;
static char* NIM_CONST TMP894[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP897[2];
static TNimNode TMP457[11];
NTI167566.size = sizeof(tkeyvaluepair167566);
NTI167566.kind = 18;
NTI167566.base = 0;
NTI167566.flags = 2;
TMP892[0] = &TMP457[1];
NTI141010.size = sizeof(NU8);
NTI141010.kind = 14;
NTI141010.base = 0;
NTI141010.flags = 3;
for (TMP895 = 0; TMP895 < 3; TMP895++) {
TMP457[TMP895+2].kind = 1;
TMP457[TMP895+2].offset = TMP895;
TMP457[TMP895+2].name = TMP894[TMP895];
TMP893[TMP895] = &TMP457[TMP895+2];
}
TMP457[5].len = 3; TMP457[5].kind = 2; TMP457[5].sons = &TMP893[0];
NTI141010.node = &TMP457[5];
TMP457[1].kind = 1;
TMP457[1].offset = offsetof(tkeyvaluepair167566, Field0);
TMP457[1].typ = (&NTI141010);
TMP457[1].name = "Field0";
TMP892[1] = &TMP457[6];
TMP457[6].kind = 1;
TMP457[6].offset = offsetof(tkeyvaluepair167566, Field1);
TMP457[6].typ = (&NTI143);
TMP457[6].name = "Field1";
TMP892[2] = &TMP457[7];
TMP457[7].kind = 1;
TMP457[7].offset = offsetof(tkeyvaluepair167566, Field2);
TMP457[7].typ = (&NTI112);
TMP457[7].name = "Field2";
TMP457[0].len = 3; TMP457[0].kind = 2; TMP457[0].sons = &TMP892[0];
NTI167566.node = &TMP457[0];
NTI167563.size = sizeof(tkeyvaluepairseq167563*);
NTI167563.kind = 24;
NTI167563.base = (&NTI167566);
NTI167563.flags = 2;
NTI167563.marker = TMP896;
NTI167560.size = sizeof(ttable167560);
NTI167560.kind = 18;
NTI167560.base = 0;
NTI167560.flags = 2;
TMP897[0] = &TMP457[9];
TMP457[9].kind = 1;
TMP457[9].offset = offsetof(ttable167560, Data);
TMP457[9].typ = (&NTI167563);
TMP457[9].name = "data";
TMP897[1] = &TMP457[10];
TMP457[10].kind = 1;
TMP457[10].offset = offsetof(ttable167560, Counter);
TMP457[10].typ = (&NTI106);
TMP457[10].name = "counter";
TMP457[8].len = 2; TMP457[8].kind = 2; TMP457[8].sons = &TMP897[0];
NTI167560.node = &TMP457[8];
}

