/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2016 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <setjmp.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/wait.h>
#include <signal.h>
#include <time.h>
#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Processobj164404 Processobj164404;
typedef struct Stringtableobj153608 Stringtableobj153608;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Streamobj157818 Streamobj157818;
typedef struct TY136002 TY136002;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Keyvaluepairseq153606 Keyvaluepairseq153606;
typedef struct Keyvaluepair153604 Keyvaluepair153604;
typedef struct Startprocessdata165703 Startprocessdata165703;
typedef struct Filestreamobj158877 Filestreamobj158877;
typedef struct Valueerror3646 Valueerror3646;
typedef struct TY165001 TY165001;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 char136Set[32];
typedef NU8 Processoption164402Set;
typedef int TY165824[2];
typedef NU8 Tnimkind3403;
typedef NU8 Tnimtypeflag3409Set;
typedef N_NIMCALL_PTR(void, TY3489) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3403 kind;
Tnimtypeflag3409Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Processobj164404  {
  TNimObject Sup;
int inhandle;
int outhandle;
int errhandle;
Streamobj157818* instream;
Streamobj157818* outstream;
Streamobj157818* errstream;
pid_t id;
int exitcode;
Processoption164402Set options;
};
typedef NU8 Tnimnodekind3405;
struct  TNimNode  {
Tnimnodekind3405 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 Processoption164402;
typedef NimStringDesc* TY195140[3];
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
typedef NimStringDesc* TY194732[1];
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e0, void* ClEnv);
void* ClEnv;
} TY17211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17211 raiseAction;
};
typedef NU8 Stringtablemode153602;
struct  Stringtableobj153608  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq153606* data;
Stringtablemode153602 mode;
};
struct Keyvaluepair153604 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Startprocessdata165703  {
NCSTRING syscommand;
NCSTRING* sysargs;
NCSTRING* sysenv;
NCSTRING workingdir;
TY165824 pstdin;
TY165824 pstdout;
TY165824 pstderr;
TY165824 perrorpipe;
NIM_BOOL optionpousepath;
NIM_BOOL optionpoparentstreams;
NIM_BOOL optionpostderrtostdout;
};
typedef NimStringDesc* TY195153[2];
typedef NU8 Filemode13009;
struct  Valueerror3646  {
  Exception Sup;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx0, void* ClEnv);
void* ClEnv;
} TY276578;
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx0, Processobj164404* p0, void* ClEnv);
void* ClEnv;
} TY276584;
typedef N_CLOSURE_PTR(void, T3891511846_24) (NI idx0);
typedef NimStringDesc* TY319494[1];
typedef N_CLOSURE_PTR(void, T3891511846_26) (NI idx0, Processobj164404* p0);
typedef N_CLOSURE_PTR(void, T3891511846_27) (NI idx0);
typedef N_CLOSURE_PTR(void, T3891511846_28) (NI idx0, Processobj164404* p0);
typedef N_CLOSURE_PTR(void, T3891511846_29) (NI idx0);
typedef N_CLOSURE_PTR(void, T3891511846_30) (NI idx0, Processobj164404* p0);
typedef N_NIMCALL_PTR(void, TY157819) (Streamobj157818* s0);
typedef N_NIMCALL_PTR(NIM_BOOL, TY157823) (Streamobj157818* s0);
typedef N_NIMCALL_PTR(void, TY157827) (Streamobj157818* s0, NI pos0);
typedef N_NIMCALL_PTR(NI, TY157832) (Streamobj157818* s0);
typedef N_NIMCALL_PTR(NI, TY157836) (Streamobj157818* s0, void* buffer0, NI buflen0);
typedef N_NIMCALL_PTR(NI, TY157842) (Streamobj157818* s0, void* buffer0, NI buflen0);
typedef N_NIMCALL_PTR(void, TY157848) (Streamobj157818* s0, void* buffer0, NI buflen0);
typedef N_NIMCALL_PTR(void, TY157854) (Streamobj157818* s0);
struct  Streamobj157818  {
  TNimObject Sup;
TY157819 closeimpl;
TY157823 atendimpl;
TY157827 setpositionimpl;
TY157832 getpositionimpl;
TY157836 readdataimpl;
TY157842 peekdataimpl;
TY157848 writedataimpl;
TY157854 flushimpl;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Filestreamobj158877  {
  Streamobj157818 Sup;
FILE* f;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
struct TY136002 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY165001 {
  TGenericSeq Sup;
  Processobj164404* data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq153606 {
  TGenericSeq Sup;
  Keyvaluepair153604 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
N_NIMCALL(NIM_BOOL, allcharsinset_109382_4286263276)(NimStringDesc* s0, char136Set theset0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_7485_1689653243)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s0, NimStringDesc* sub0, NimStringDesc* by0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T3891511846_10)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NOINLINE(void, raiseoserror_131603_2125978480)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_131619_2125978480)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
N_NIMCALL(NCSTRING*, alloccstringarray_15601_1689653243)(NimStringDesc** a0, NI a0Len0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s0);
N_NIMCALL(NCSTRING*, envtocstringarray_165636_3891511846)(void);
N_NIMCALL(void, getenvvarsc_136202_2125978480)(void);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s0, NIM_CHAR sub0, NI start0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s0, NI start_79210_1689653243, NI last0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s0, NI first0, NI last0);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s0, NI start0);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s0, NI first0);
N_NOCONV(void*, alloc0_7817_1689653243)(NI size0);
N_NOCONV(void*, alloc_7801_1689653243)(NI size0);
N_NIMCALL(NCSTRING*, envtocstringarray_165603_3891511846)(Stringtableobj153608* t0);
N_NIMCALL(NI, nstlen)(Stringtableobj153608* t0);
N_NIMCALL(pid_t, startprocessauxfork_165801_3891511846)(Startprocessdata165703* data0);
N_CDECL(void, startprocessafterfork_165804_3891511846)(Startprocessdata165703* data0);
N_NIMCALL(void, startprocessfail_166616_3891511846)(Startprocessdata165703* data0);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a0, NI a0Len0, NimStringDesc* sep0);
N_NIMCALL(void, dealloccstringarray_15829_1689653243)(NCSTRING* a0);
N_NIMCALL(void, createstream_167836_3891511846)(Streamobj157818** stream0, int* handle0, Filemode13009 filemode0);
N_NIMCALL(NIM_BOOL, open_14811_1689653243)(FILE** f0, int filehandle0, Filemode13009 mode0);
N_NIMCALL(Filestreamobj158877*, newfilestream_158930_1780494535)(FILE* f0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(NI64, ntDiffTime)(time_t a0, time_t b0);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a0, time_t b0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(void, T3891511846_22)(void* p, NI op);
N_NIMCALL(Processobj164404*, nospstartProcess)(NimStringDesc* command0, NimStringDesc* workingdir0, NimStringDesc** args0, NI args0Len0, Stringtableobj153608* env0, Processoption164402Set options0);
static N_INLINE(void, asgnRef)(void** dest0, void* src0);
static N_INLINE(void, incref_53419_1689653243)(Cell47305* c0);
static N_INLINE(void, decref_53001_1689653243)(Cell47305* c0);
N_NIMCALL(void, nossleep)(NI milsecs0);
N_NIMCALL(NIM_BOOL, nosprunning)(Processobj164404* p0);
N_NIMCALL(NI, nospwaitForExit)(Processobj164404* p0, NI timeout0);
N_NIMCALL(void, nospclose)(Processobj164404* p0);
N_NIMCALL(void, close_157873_1780494535)(Streamobj157818* s0);
STRING_LITERAL(T3891511846_2, "\'\'", 2);
static NIM_CONST char136Set T3891511846_3 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(T3891511846_4, "\'", 1);
STRING_LITERAL(T3891511846_5, "\'\"\'\"\'", 5);
STRING_LITERAL(T3891511846_11, "", 0);
STRING_LITERAL(T3891511846_12, "/bin/sh", 7);
STRING_LITERAL(T3891511846_13, "-c", 2);
STRING_LITERAL(T3891511846_15, "=", 1);
STRING_LITERAL(T3891511846_18, "Could not find command: \'$1\'. OS error: $2", 42);
STRING_LITERAL(T3891511846_19, " ", 1);
STRING_LITERAL(T3891511846_21, "System time was modified", 24);
static NIM_CONST TY276578 T3891511846_23 = {NIM_NIL,NIM_NIL};
static NIM_CONST TY276584 T3891511846_25 = {NIM_NIL,NIM_NIL};
extern TNimType NTI3608; /* RootObj */
TNimType NTI164404; /* ProcessObj */
extern TNimType NTI13011; /* FileHandle */
extern TNimType NTI157816; /* Stream */
extern TNimType NTI120676; /* Pid */
extern TNimType NTI7408; /* cint */
TNimType NTI164402; /* ProcessOption */
TNimType NTI164628; /* set[ProcessOption] */
TNimType NTI164406; /* Process */
extern TNimType NTI136002; /* seq[string] */
extern Gcheap49818 gch_49858_1689653243;
extern TSafePoint* exchandler_18837_1689653243;
extern TY136002* environment_136003_2125978480;
extern TNimType NTI23025; /* ref ValueError */
extern TNimType NTI3646; /* ValueError */
TNimType NTI165001; /* seq[Process] */

static N_INLINE(void, copymem_7485_1689653243)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_7485_1689653243(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s0) {
	NimStringDesc* result0;
	NIM_BOOL safe0;
{	result0 = (NimStringDesc*)0;
	{
		if (!((s0 ? s0->Sup.len : 0) == ((NI) 0))) goto LA3;
		result0 = copyString(((NimStringDesc*) &T3891511846_2));
		goto BeforeRet;
	}
	LA3: ;
	safe0 = allcharsinset_109382_4286263276(s0, T3891511846_3);
	{
		if (!safe0) goto LA7;
		result0 = copyString(s0);
		goto BeforeRet;
	}
	goto LA5;
	LA7: ;
	{
		NimStringDesc* LOC10;
		NimStringDesc* LOC11;
		LOC10 = (NimStringDesc*)0;
		LOC11 = (NimStringDesc*)0;
		LOC11 = nsuReplaceStr(s0, ((NimStringDesc*) &T3891511846_4), ((NimStringDesc*) &T3891511846_5));
		LOC10 = rawNewString(LOC11->Sup.len + 2);
appendString(LOC10, ((NimStringDesc*) &T3891511846_4));
appendString(LOC10, LOC11);
appendString(LOC10, ((NimStringDesc*) &T3891511846_4));
		result0 = LOC10;
		goto BeforeRet;
	}
	LA5: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s0) {
	NimStringDesc* result0;
{	result0 = (NimStringDesc*)0;
	result0 = nospquoteShellPosix(s0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}
N_NIMCALL(void, T3891511846_10)(void* p, NI op) {
	Processobj164404* a;
	a = (Processobj164404*)p;
	nimGCvisit((void*)(*a).instream, op);
	nimGCvisit((void*)(*a).outstream, op);
	nimGCvisit((void*)(*a).errstream, op);
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	result0 = (Cell47305*)0;
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47305* c0;
	c0 = usrtocell_51440_1689653243(p0);
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA3;
		rtladdzct_52601_1689653243(c0);
	}
	LA3: ;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s0) {
	(*s0).hasRaiseAction = NIM_FALSE;
	(*s0).prev = exchandler_18837_1689653243;
	exchandler_18837_1689653243 = s0;
}

N_NIMCALL(NCSTRING*, envtocstringarray_165636_3891511846)(void) {
	NCSTRING* result0;
	NI counter0;
	void* LOC5;
	NI i0;
	result0 = (NCSTRING*)0;
	counter0 = ((NI) 0);
	{
		NimStringDesc* key_165640_3891511846;
		NimStringDesc* val_165641_3891511846;
		key_165640_3891511846 = (NimStringDesc*)0;
		val_165641_3891511846 = (NimStringDesc*)0;
		getenvvarsc_136202_2125978480();
		{
			NI i_165670_3891511846;
			NI HEX3Atmp_165672_3891511846;
			NI res_165674_3891511846;
			i_165670_3891511846 = (NI)0;
			HEX3Atmp_165672_3891511846 = (NI)0;
			HEX3Atmp_165672_3891511846 = (environment_136003_2125978480 ? (environment_136003_2125978480->Sup.len-1) : -1);
			res_165674_3891511846 = ((NI) 0);
			{
				while (1) {
					NI p_165678_3891511846;
					if (!(res_165674_3891511846 <= HEX3Atmp_165672_3891511846)) goto LA4;
					i_165670_3891511846 = res_165674_3891511846;
					p_165678_3891511846 = nsuFindChar(environment_136003_2125978480->data[i_165670_3891511846], 61, ((NI) 0));
					key_165640_3891511846 = copyStrLast(environment_136003_2125978480->data[i_165670_3891511846], ((NI) 0), (NI)(p_165678_3891511846 - ((NI) 1)));
					val_165641_3891511846 = copyStr(environment_136003_2125978480->data[i_165670_3891511846], (NI)(p_165678_3891511846 + ((NI) 1)));
					counter0 += ((NI) 1);
					res_165674_3891511846 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	LOC5 = (void*)0;
	LOC5 = alloc0_7817_1689653243(((NI) ((NI)((NI)(counter0 + ((NI) 1)) * ((NI) 4)))));
	result0 = ((NCSTRING*) (LOC5));
	i0 = ((NI) 0);
	{
		NimStringDesc* key_165653_3891511846;
		NimStringDesc* val_165654_3891511846;
		key_165653_3891511846 = (NimStringDesc*)0;
		val_165654_3891511846 = (NimStringDesc*)0;
		getenvvarsc_136202_2125978480();
		{
			NI i_165691_3891511846;
			NI HEX3Atmp_165693_3891511846;
			NI res_165695_3891511846;
			i_165691_3891511846 = (NI)0;
			HEX3Atmp_165693_3891511846 = (NI)0;
			HEX3Atmp_165693_3891511846 = (environment_136003_2125978480 ? (environment_136003_2125978480->Sup.len-1) : -1);
			res_165695_3891511846 = ((NI) 0);
			{
				while (1) {
					NI p_165699_3891511846;
					NimStringDesc* x0;
					NimStringDesc* LOC10;
					void* LOC11;
					if (!(res_165695_3891511846 <= HEX3Atmp_165693_3891511846)) goto LA9;
					i_165691_3891511846 = res_165695_3891511846;
					p_165699_3891511846 = nsuFindChar(environment_136003_2125978480->data[i_165691_3891511846], 61, ((NI) 0));
					key_165653_3891511846 = copyStrLast(environment_136003_2125978480->data[i_165691_3891511846], ((NI) 0), (NI)(p_165699_3891511846 - ((NI) 1)));
					val_165654_3891511846 = copyStr(environment_136003_2125978480->data[i_165691_3891511846], (NI)(p_165699_3891511846 + ((NI) 1)));
					LOC10 = (NimStringDesc*)0;
					LOC10 = rawNewString(key_165653_3891511846->Sup.len + val_165654_3891511846->Sup.len + 1);
appendString(LOC10, key_165653_3891511846);
appendString(LOC10, ((NimStringDesc*) &T3891511846_15));
appendString(LOC10, val_165654_3891511846);
					x0 = LOC10;
					LOC11 = (void*)0;
					LOC11 = alloc_7801_1689653243(((NI) ((NI)((x0 ? x0->Sup.len : 0) + ((NI) 1)))));
					result0[(i0)- 0] = ((NCSTRING) (LOC11));
					copymem_7485_1689653243(((void*) (result0[(i0)- 0])), ((void*) ((&x0->data[((NI) 0)]))), ((NI) ((NI)((x0 ? x0->Sup.len : 0) + ((NI) 1)))));
					i0 += ((NI) 1);
					res_165695_3891511846 += ((NI) 1);
				} LA9: ;
			}
		}
	}
	return result0;
}

N_NIMCALL(NCSTRING*, envtocstringarray_165603_3891511846)(Stringtableobj153608* t0) {
	NCSTRING* result0;
	NI LOC1;
	void* LOC2;
	NI i0;
	result0 = (NCSTRING*)0;
	LOC1 = (NI)0;
	LOC1 = nstlen(t0);
	LOC2 = (void*)0;
	LOC2 = alloc0_7817_1689653243(((NI) ((NI)((NI)(LOC1 + ((NI) 1)) * ((NI) 4)))));
	result0 = ((NCSTRING*) (LOC2));
	i0 = ((NI) 0);
	{
		NimStringDesc* key_165609_3891511846;
		NimStringDesc* val_165610_3891511846;
		key_165609_3891511846 = (NimStringDesc*)0;
		val_165610_3891511846 = (NimStringDesc*)0;
		{
			NI h_165629_3891511846;
			NI HEX3Atmp_165631_3891511846;
			NI res_165633_3891511846;
			h_165629_3891511846 = (NI)0;
			HEX3Atmp_165631_3891511846 = (NI)0;
			HEX3Atmp_165631_3891511846 = ((*t0).data ? ((*t0).data->Sup.len-1) : -1);
			res_165633_3891511846 = ((NI) 0);
			{
				while (1) {
					if (!(res_165633_3891511846 <= HEX3Atmp_165631_3891511846)) goto LA6;
					h_165629_3891511846 = res_165633_3891511846;
					{
						NimStringDesc* x0;
						NimStringDesc* LOC11;
						void* LOC12;
						if (!!((*t0).data->data[h_165629_3891511846].Field0 == 0)) goto LA9;
						key_165609_3891511846 = (*t0).data->data[h_165629_3891511846].Field0;
						val_165610_3891511846 = (*t0).data->data[h_165629_3891511846].Field1;
						LOC11 = (NimStringDesc*)0;
						LOC11 = rawNewString(key_165609_3891511846->Sup.len + val_165610_3891511846->Sup.len + 1);
appendString(LOC11, key_165609_3891511846);
appendString(LOC11, ((NimStringDesc*) &T3891511846_15));
appendString(LOC11, val_165610_3891511846);
						x0 = LOC11;
						LOC12 = (void*)0;
						LOC12 = alloc_7801_1689653243(((NI) ((NI)((x0 ? x0->Sup.len : 0) + ((NI) 1)))));
						result0[(i0)- 0] = ((NCSTRING) (LOC12));
						copymem_7485_1689653243(((void*) (result0[(i0)- 0])), ((void*) ((&x0->data[((NI) 0)]))), ((NI) ((NI)((x0 ? x0->Sup.len : 0) + ((NI) 1)))));
						i0 += ((NI) 1);
					}
					LA9: ;
					res_165633_3891511846 += ((NI) 1);
				} LA6: ;
			}
		}
	}
	return result0;
}

N_NIMCALL(void, startprocessfail_166616_3891511846)(Startprocessdata165703* data0) {
	int error0;
	NI LOC1;
	error0 = errno;
	LOC1 = (NI)0;
	LOC1 = write((*data0).perrorpipe[(((NI) 1))- 0], ((void*) ((&error0))), ((NI) 4));
	_exit(((NI) 1));
}

N_CDECL(void, startprocessafterfork_165804_3891511846)(Startprocessdata165703* data0) {
	int LOC42;
	int LOC43;
	{
		int LOC5;
		int LOC11;
		int LOC17;
		if (!!((*data0).optionpoparentstreams)) goto LA3;
		LOC5 = (int)0;
		LOC5 = close((*data0).pstdin[(((NI) 1))- 0]);
		{
			int LOC8;
			LOC8 = (int)0;
			LOC8 = dup2((*data0).pstdin[(((NI) 0))- 0], ((int) 0));
			if (!(LOC8 < ((NI32) 0))) goto LA9;
			startprocessfail_166616_3891511846(data0);
		}
		LA9: ;
		LOC11 = (int)0;
		LOC11 = close((*data0).pstdout[(((NI) 0))- 0]);
		{
			int LOC14;
			LOC14 = (int)0;
			LOC14 = dup2((*data0).pstdout[(((NI) 1))- 0], ((int) 1));
			if (!(LOC14 < ((NI32) 0))) goto LA15;
			startprocessfail_166616_3891511846(data0);
		}
		LA15: ;
		LOC17 = (int)0;
		LOC17 = close((*data0).pstderr[(((NI) 0))- 0]);
		{
			if (!(*data0).optionpostderrtostdout) goto LA20;
			{
				int LOC24;
				LOC24 = (int)0;
				LOC24 = dup2((*data0).pstdout[(((NI) 1))- 0], ((int) 2));
				if (!(LOC24 < ((NI32) 0))) goto LA25;
				startprocessfail_166616_3891511846(data0);
			}
			LA25: ;
		}
		goto LA18;
		LA20: ;
		{
			{
				int LOC30;
				LOC30 = (int)0;
				LOC30 = dup2((*data0).pstderr[(((NI) 1))- 0], ((int) 2));
				if (!(LOC30 < ((NI32) 0))) goto LA31;
				startprocessfail_166616_3891511846(data0);
			}
			LA31: ;
		}
		LA18: ;
	}
	LA3: ;
	{
		if (!(((NI) 0) < ((*data0).workingdir ? strlen((*data0).workingdir) : 0))) goto LA35;
		{
			int LOC39;
			LOC39 = (int)0;
			LOC39 = chdir((*data0).workingdir);
			if (!(LOC39 < ((NI32) 0))) goto LA40;
			startprocessfail_166616_3891511846(data0);
		}
		LA40: ;
	}
	LA35: ;
	LOC42 = (int)0;
	LOC42 = close((*data0).perrorpipe[(((NI) 0))- 0]);
	LOC43 = (int)0;
	LOC43 = fcntl((*data0).perrorpipe[(((NI) 1))- 0], F_SETFD, FD_CLOEXEC);
	{
		int LOC48;
		if (!(*data0).optionpousepath) goto LA46;
		LOC48 = (int)0;
		LOC48 = execvpe((*data0).syscommand, (*data0).sysargs, (*data0).sysenv);
	}
	goto LA44;
	LA46: ;
	{
		int LOC50;
		LOC50 = (int)0;
		LOC50 = execve((*data0).syscommand, (*data0).sysargs, (*data0).sysenv);
	}
	LA44: ;
	startprocessfail_166616_3891511846(data0);
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_18837_1689653243 = (*exchandler_18837_1689653243).prev;
}

N_NIMCALL(pid_t, startprocessauxfork_165801_3891511846)(Startprocessdata165703* data0) {
	pid_t volatile result0;
	TSafePoint T3891511846_17;
{	result0 = (pid_t)0;
	{
		int LOC3;
		NI32 LOC6;
		LOC3 = (int)0;
		LOC3 = pipe((*data0).perrorpipe);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = (NI32)0;
		LOC6 = oslasterror_131619_2125978480();
		raiseoserror_131603_2125978480(LOC6, ((NimStringDesc*) &T3891511846_11));
	}
	LA4: ;
	pushSafePoint(&T3891511846_17);
	T3891511846_17.status = setjmp(T3891511846_17.context);
	if (T3891511846_17.status == 0) {
		pid_t volatile pid0;
		Startprocessdata165703 datacopy0;
		int LOC12;
		int error0;
		NI sizeread0;
		int LOC26;
		pid0 = (pid_t)0;
		datacopy0 = (*data0);
		pid0 = fork();
		{
			if (!(pid0 == ((NI) 0))) goto LA10;
			startprocessafterfork_165804_3891511846((&datacopy0));
			_exit(((NI) 1));
		}
		LA10: ;
		LOC12 = (int)0;
		LOC12 = close((*data0).perrorpipe[(((NI) 1))- 0]);
		{
			NI32 LOC17;
			if (!(pid0 < ((NI) 0))) goto LA15;
			LOC17 = (NI32)0;
			LOC17 = oslasterror_131619_2125978480();
			raiseoserror_131603_2125978480(LOC17, ((NimStringDesc*) &T3891511846_11));
		}
		LA15: ;
		error0 = (int)0;
		sizeread0 = read((*data0).perrorpipe[(((NI) 0))- 0], ((void*) ((&error0))), ((NI) 4));
		{
			NI32 LOC22;
			TY195153 LOC23;
			NCSTRING LOC24;
			NimStringDesc* LOC25;
			if (!(sizeread0 == ((NI) 4))) goto LA20;
			LOC22 = (NI32)0;
			LOC22 = oslasterror_131619_2125978480();
			memset((void*)LOC23, 0, sizeof(LOC23));
			LOC23[0] = cstrToNimstr((*data0).syscommand);
			LOC24 = (NCSTRING)0;
			LOC24 = strerror(error0);
			LOC23[1] = cstrToNimstr(LOC24);
			LOC25 = (NimStringDesc*)0;
			LOC25 = nsuFormatOpenArray(((NimStringDesc*) &T3891511846_18), LOC23, 2);
			raiseoserror_131603_2125978480(LOC22, LOC25);
		}
		LA20: ;
		result0 = pid0;
		popSafePoint();
		LOC26 = (int)0;
		LOC26 = close((*data0).perrorpipe[(((NI) 0))- 0]);
		goto BeforeRet;
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		int LOC29;
		LOC29 = (int)0;
		LOC29 = close((*data0).perrorpipe[(((NI) 0))- 0]);
	}
	if (T3891511846_17.status != 0) reraiseException();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Processobj164404*, nospstartProcess)(NimStringDesc* command0, NimStringDesc* workingdir0, NimStringDesc** args0, NI args0Len0, Stringtableobj153608* env0, Processoption164402Set options0) {
	Processobj164404* result0;
	TY165824 pstdin0;
	TY165824 pstdout0;
	TY165824 pstderr0;
	NimStringDesc* syscommand0;
	TY136002* sysargsraw0;
	pid_t volatile pid0;
	NCSTRING* sysargs0;
	TSafePoint T3891511846_14;
	result0 = (Processobj164404*)0;
	memset((void*)pstdin0, 0, sizeof(pstdin0));
	memset((void*)pstdout0, 0, sizeof(pstdout0));
	memset((void*)pstderr0, 0, sizeof(pstderr0));
	result0 = (Processobj164404*) newObj((&NTI164406), sizeof(Processobj164404));
	(*result0).Sup.m_type = (&NTI164404);
	(*result0).options = options0;
	(*result0).exitcode = ((int) -3);
	{
		if (!!(((options0 &(1U<<((NU)(((Processoption164402) 4))&7U)))!=0))) goto LA3;
		{
			NIM_BOOL LOC7;
			NIM_BOOL LOC8;
			int LOC9;
			int LOC11;
			int LOC13;
			NI32 LOC16;
			LOC7 = (NIM_BOOL)0;
			LOC8 = (NIM_BOOL)0;
			LOC9 = (int)0;
			LOC9 = pipe(pstdin0);
			LOC8 = !((LOC9 == ((NI32) 0)));
			if (LOC8) goto LA10;
			LOC11 = (int)0;
			LOC11 = pipe(pstdout0);
			LOC8 = !((LOC11 == ((NI32) 0)));
			LA10: ;
			LOC7 = LOC8;
			if (LOC7) goto LA12;
			LOC13 = (int)0;
			LOC13 = pipe(pstderr0);
			LOC7 = !((LOC13 == ((NI32) 0)));
			LA12: ;
			if (!LOC7) goto LA14;
			LOC16 = (NI32)0;
			LOC16 = oslasterror_131619_2125978480();
			raiseoserror_131603_2125978480(LOC16, ((NimStringDesc*) &T3891511846_11));
		}
		LA14: ;
	}
	LA3: ;
	syscommand0 = (NimStringDesc*)0;
	sysargsraw0 = (TY136002*)0;
	{
		TY195140 LOC21;
		NimStringDesc* LOC22;
		NimStringDesc* LOC23;
		NimStringDesc* LOC24;
		if (!((options0 &(1U<<((NU)(((Processoption164402) 2))&7U)))!=0)) goto LA19;
		syscommand0 = copyString(((NimStringDesc*) &T3891511846_12));
		sysargsraw0 = (TY136002*) newSeq((&NTI136002), 3);
		memset((void*)LOC21, 0, sizeof(LOC21));
		LOC21[0] = copyString(syscommand0);
		LOC21[1] = copyString(((NimStringDesc*) &T3891511846_13));
		LOC21[2] = copyString(command0);
		LOC22 = (NimStringDesc*)0;
		LOC22 = sysargsraw0->data[0]; sysargsraw0->data[0] = copyStringRC1(LOC21[0]);
		if (LOC22) nimGCunrefNoCycle(LOC22);
		LOC23 = (NimStringDesc*)0;
		LOC23 = sysargsraw0->data[1]; sysargsraw0->data[1] = copyStringRC1(LOC21[1]);
		if (LOC23) nimGCunrefNoCycle(LOC23);
		LOC24 = (NimStringDesc*)0;
		LOC24 = sysargsraw0->data[2]; sysargsraw0->data[2] = copyStringRC1(LOC21[2]);
		if (LOC24) nimGCunrefNoCycle(LOC24);
	}
	goto LA17;
	LA19: ;
	{
		TY194732 LOC26;
		NimStringDesc* LOC27;
		syscommand0 = copyString(command0);
		sysargsraw0 = (TY136002*) newSeq((&NTI136002), 1);
		memset((void*)LOC26, 0, sizeof(LOC26));
		LOC26[0] = copyString(command0);
		LOC27 = (NimStringDesc*)0;
		LOC27 = sysargsraw0->data[0]; sysargsraw0->data[0] = copyStringRC1(LOC26[0]);
		if (LOC27) nimGCunrefNoCycle(LOC27);
		{
			NimStringDesc* arg_166021_3891511846;
			NI i_166279_3891511846;
			arg_166021_3891511846 = (NimStringDesc*)0;
			i_166279_3891511846 = ((NI) 0);
			{
				while (1) {
					NimStringDesc* LOC31;
					if (!(i_166279_3891511846 < args0Len0)) goto LA30;
					arg_166021_3891511846 = args0[i_166279_3891511846];
					sysargsraw0 = (TY136002*) incrSeqV2(&(sysargsraw0)->Sup, sizeof(NimStringDesc*));
					LOC31 = (NimStringDesc*)0;
					LOC31 = sysargsraw0->data[sysargsraw0->Sup.len]; sysargsraw0->data[sysargsraw0->Sup.len] = copyStringRC1(arg_166021_3891511846);
					if (LOC31) nimGCunrefNoCycle(LOC31);
					++sysargsraw0->Sup.len;
					i_166279_3891511846 += ((NI) 1);
				} LA30: ;
			}
		}
	}
	LA17: ;
	pid0 = (pid_t)0;
	sysargs0 = alloccstringarray_15601_1689653243(sysargsraw0->data, sysargsraw0->Sup.len);
	pushSafePoint(&T3891511846_14);
	T3891511846_14.status = setjmp(T3891511846_14.context);
	if (T3891511846_14.status == 0) {
		NCSTRING* sysenv0;
		TSafePoint T3891511846_16;
		{
			if (!(env0 == NIM_NIL)) goto LA35;
			sysenv0 = envtocstringarray_165636_3891511846();
		}
		goto LA33;
		LA35: ;
		{
			sysenv0 = envtocstringarray_165603_3891511846(env0);
		}
		LA33: ;
		pushSafePoint(&T3891511846_16);
		T3891511846_16.status = setjmp(T3891511846_16.context);
		if (T3891511846_16.status == 0) {
			Startprocessdata165703 data0;
			memset((void*)(&data0), 0, sizeof(data0));
			data0.syscommand = syscommand0->data;
			data0.sysargs = sysargs0;
			data0.sysenv = sysenv0;
			memcpy((void*)data0.pstdin, (NIM_CONST void*)pstdin0, sizeof(TY165824));
			memcpy((void*)data0.pstdout, (NIM_CONST void*)pstdout0, sizeof(TY165824));
			memcpy((void*)data0.pstderr, (NIM_CONST void*)pstderr0, sizeof(TY165824));
			data0.optionpoparentstreams = ((options0 &(1U<<((NU)(((Processoption164402) 4))&7U)))!=0);
			data0.optionpousepath = ((options0 &(1U<<((NU)(((Processoption164402) 1))&7U)))!=0);
			data0.optionpostderrtostdout = ((options0 &(1U<<((NU)(((Processoption164402) 3))&7U)))!=0);
			data0.workingdir = workingdir0->data;
			pid0 = startprocessauxfork_165801_3891511846((&data0));
			{
				NimStringDesc* LOC43;
				if (!((options0 &(1U<<((NU)(((Processoption164402) 0))&7U)))!=0)) goto LA41;
				LOC43 = (NimStringDesc*)0;
				LOC43 = nsuJoinSep(args0, args0Len0, ((NimStringDesc*) &T3891511846_19));
				printf("%s%s%s\012", command0? (command0)->data:"nil", ((NimStringDesc*) &T3891511846_19)? (((NimStringDesc*) &T3891511846_19))->data:"nil", LOC43? (LOC43)->data:"nil");
				fflush(stdout);
			}
			LA41: ;
			(*result0).id = pid0;
			{
				if (!((options0 &(1U<<((NU)(((Processoption164402) 4))&7U)))!=0)) goto LA46;
				(*result0).inhandle = ((int) 0);
				(*result0).outhandle = ((int) 1);
				{
					if (!((options0 &(1U<<((NU)(((Processoption164402) 3))&7U)))!=0)) goto LA50;
					(*result0).errhandle = (*result0).outhandle;
				}
				goto LA48;
				LA50: ;
				{
					(*result0).errhandle = ((int) 2);
				}
				LA48: ;
			}
			goto LA44;
			LA46: ;
			{
				int LOC60;
				int LOC61;
				int LOC62;
				(*result0).inhandle = pstdin0[(((NI) 1))- 0];
				(*result0).outhandle = pstdout0[(((NI) 0))- 0];
				{
					int LOC58;
					if (!((options0 &(1U<<((NU)(((Processoption164402) 3))&7U)))!=0)) goto LA56;
					(*result0).errhandle = (*result0).outhandle;
					LOC58 = (int)0;
					LOC58 = close(pstderr0[(((NI) 0))- 0]);
				}
				goto LA54;
				LA56: ;
				{
					(*result0).errhandle = pstderr0[(((NI) 0))- 0];
				}
				LA54: ;
				LOC60 = (int)0;
				LOC60 = close(pstderr0[(((NI) 1))- 0]);
				LOC61 = (int)0;
				LOC61 = close(pstdin0[(((NI) 0))- 0]);
				LOC62 = (int)0;
				LOC62 = close(pstdout0[(((NI) 1))- 0]);
			}
			LA44: ;
			popSafePoint();
		}
		else {
			popSafePoint();
		}
		{
			dealloccstringarray_15829_1689653243(sysenv0);
		}
		if (T3891511846_16.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		dealloccstringarray_15829_1689653243(sysargs0);
	}
	if (T3891511846_14.status != 0) reraiseException();
	return result0;
}

N_NIMCALL(void, createstream_167836_3891511846)(Streamobj157818** stream0, int* handle0, Filemode13009 filemode0) {
	FILE* f0;
	Filestreamobj158877* LOC7;
	f0 = (FILE*)0;
	{
		NIM_BOOL LOC3;
		NI32 LOC6;
		LOC3 = (NIM_BOOL)0;
		LOC3 = open_14811_1689653243(&f0, (*handle0), filemode0);
		if (!!(LOC3)) goto LA4;
		LOC6 = (NI32)0;
		LOC6 = oslasterror_131619_2125978480();
		raiseoserror_131603_2125978480(LOC6, ((NimStringDesc*) &T3891511846_11));
	}
	LA4: ;
	LOC7 = (Filestreamobj158877*)0;
	LOC7 = newfilestream_158930_1780494535(f0);
	unsureAsgnRef((void**) (&(*stream0)), &LOC7->Sup);
}

N_NIMCALL(Streamobj157818*, nospinputStream)(Processobj164404* p0) {
	Streamobj157818* result0;
{	result0 = (Streamobj157818*)0;
	{
		if (!((*p0).instream == NIM_NIL)) goto LA3;
		createstream_167836_3891511846(&(*p0).instream, (&(*p0).inhandle), ((Filemode13009) 1));
	}
	LA3: ;
	result0 = (*p0).instream;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Streamobj157818*, nospoutputStream)(Processobj164404* p0) {
	Streamobj157818* result0;
{	result0 = (Streamobj157818*)0;
	{
		if (!((*p0).outstream == NIM_NIL)) goto LA3;
		createstream_167836_3891511846(&(*p0).outstream, (&(*p0).outhandle), ((Filemode13009) 0));
	}
	LA3: ;
	result0 = (*p0).outstream;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, nospwaitForExit)(Processobj164404* p0, NI timeout0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!!(((*p0).exitcode == ((NI32) -3)))) goto LA3;
		result0 = ((NI) ((*p0).exitcode));
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(timeout0 == ((NI) -1))) goto LA7;
		{
			pid_t LOC11;
			NI32 LOC14;
			LOC11 = (pid_t)0;
			LOC11 = waitpid((*p0).id, (&(*p0).exitcode), ((int) 0));
			if (!(LOC11 < ((NI) 0))) goto LA12;
			(*p0).exitcode = ((int) -3);
			LOC14 = (NI32)0;
			LOC14 = oslasterror_131619_2125978480();
			raiseoserror_131603_2125978480(LOC14, ((NimStringDesc*) &T3891511846_11));
		}
		LA12: ;
	}
	goto LA5;
	LA7: ;
	{
		sigset_t nmask0;
		sigset_t omask0;
		siginfo_t sinfo0;
		struct timespec stspec0;
		struct timespec enspec0;
		struct timespec tmspec0;
		int LOC16;
		int LOC17;
		int LOC18;
		TSafePoint T3891511846_20;
		memset((void*)(&nmask0), 0, sizeof(nmask0));
		memset((void*)(&omask0), 0, sizeof(omask0));
		memset((void*)(&sinfo0), 0, sizeof(sinfo0));
		memset((void*)(&stspec0), 0, sizeof(stspec0));
		memset((void*)(&enspec0), 0, sizeof(enspec0));
		memset((void*)(&tmspec0), 0, sizeof(tmspec0));
		LOC16 = (int)0;
		LOC16 = sigemptyset((&nmask0));
		LOC17 = (int)0;
		LOC17 = sigemptyset((&omask0));
		LOC18 = (int)0;
		LOC18 = sigaddset((&nmask0), SIGCHLD);
		{
			int LOC21;
			NI32 LOC24;
			LOC21 = (int)0;
			LOC21 = sigprocmask(SIG_BLOCK, (&nmask0), (&omask0));
			if (!(LOC21 == ((NI32) -1))) goto LA22;
			LOC24 = (NI32)0;
			LOC24 = oslasterror_131619_2125978480();
			raiseoserror_131603_2125978480(LOC24, ((NimStringDesc*) &T3891511846_11));
		}
		LA22: ;
		{
			if (!(((NI) 1000) <= timeout0)) goto LA27;
			tmspec0.tv_sec = (NI)(timeout0 / ((NI) 1000));
			tmspec0.tv_nsec = (NI)((NI)((NU32)(timeout0) % (NU32)(((NI) 1000))) * ((NI) 1000000));
		}
		goto LA25;
		LA27: ;
		{
			tmspec0.tv_sec = ((time_t) 0);
			tmspec0.tv_nsec = (NI)(timeout0 * ((NI) 1000000));
		}
		LA25: ;
		pushSafePoint(&T3891511846_20);
		T3891511846_20.status = setjmp(T3891511846_20.context);
		if (T3891511846_20.status == 0) {
			{
				int LOC33;
				NI32 LOC36;
				LOC33 = (int)0;
				LOC33 = clock_gettime(((clockid_t) (CLOCK_REALTIME)), (&stspec0));
				if (!(LOC33 == ((NI32) -1))) goto LA34;
				LOC36 = (NI32)0;
				LOC36 = oslasterror_131619_2125978480();
				raiseoserror_131603_2125978480(LOC36, ((NimStringDesc*) &T3891511846_11));
			}
			LA34: ;
			{
				while (1) {
					int res0;
					res0 = sigtimedwait((&nmask0), (&sinfo0), (&tmspec0));
					{
						if (!(res0 == SIGCHLD)) goto LA41;
						{
							if (!(sinfo0.si_pid == (*p0).id)) goto LA45;
							{
								pid_t LOC49;
								NI32 LOC52;
								LOC49 = (pid_t)0;
								LOC49 = waitpid((*p0).id, (&(*p0).exitcode), ((int) 0));
								if (!(LOC49 < ((NI) 0))) goto LA50;
								(*p0).exitcode = ((int) -3);
								LOC52 = (NI32)0;
								LOC52 = oslasterror_131619_2125978480();
								raiseoserror_131603_2125978480(LOC52, ((NimStringDesc*) &T3891511846_11));
							}
							LA50: ;
							goto LA37;
						}
						goto LA43;
						LA45: ;
						{
							NI volatile diff_167625_3891511846;
							struct timespec b_167627_3891511846;
							NI64 LOC60;
							NI64 LOC73;
							{
								int LOC56;
								NI32 LOC59;
								LOC56 = (int)0;
								LOC56 = clock_gettime(((clockid_t) (CLOCK_REALTIME)), (&enspec0));
								if (!(LOC56 == ((NI32) -1))) goto LA57;
								LOC59 = (NI32)0;
								LOC59 = oslasterror_131619_2125978480();
								raiseoserror_131603_2125978480(LOC59, ((NimStringDesc*) &T3891511846_11));
							}
							LA57: ;
							diff_167625_3891511846 = (NI)0;
							memset((void*)(&b_167627_3891511846), 0, sizeof(b_167627_3891511846));
							b_167627_3891511846.tv_sec = enspec0.tv_sec;
							b_167627_3891511846.tv_nsec = enspec0.tv_nsec;
							LOC60 = (NI64)0;
							LOC60 = ntDiffTime(enspec0.tv_sec, stspec0.tv_sec);
							enspec0.tv_sec = ((time_t) (LOC60));
							{
								if (!(stspec0.tv_nsec <= enspec0.tv_nsec)) goto LA63;
								enspec0.tv_nsec -= stspec0.tv_nsec;
							}
							goto LA61;
							LA63: ;
							{
								{
									NIM_BOOL LOC68;
									Valueerror3646* volatile e_167639_3891511846;
									NimStringDesc* LOC71;
									LOC68 = (NIM_BOOL)0;
									LOC68 = ntEqTime(enspec0.tv_sec, ((time_t) 0));
									if (!LOC68) goto LA69;
									e_167639_3891511846 = (Valueerror3646*)0;
									e_167639_3891511846 = (Valueerror3646*) newObj((&NTI23025), sizeof(Valueerror3646));
									(*e_167639_3891511846).Sup.Sup.m_type = (&NTI3646);
									LOC71 = (NimStringDesc*)0;
									LOC71 = (*e_167639_3891511846).Sup.message; (*e_167639_3891511846).Sup.message = copyStringRC1(((NimStringDesc*) &T3891511846_21));
									if (LOC71) nimGCunrefNoCycle(LOC71);
									raiseException((Exception*)e_167639_3891511846, "ValueError");
								}
								goto LA66;
								LA69: ;
								{
									diff_167625_3891511846 = (NI)(stspec0.tv_nsec - enspec0.tv_nsec);
									enspec0.tv_nsec = (NI)(((NI) 1000000000) - diff_167625_3891511846);
								}
								LA66: ;
							}
							LA61: ;
							LOC73 = (NI64)0;
							LOC73 = ntDiffTime(tmspec0.tv_sec, enspec0.tv_sec);
							tmspec0.tv_sec = ((time_t) (LOC73));
							{
								if (!(enspec0.tv_nsec <= tmspec0.tv_nsec)) goto LA76;
								tmspec0.tv_nsec -= enspec0.tv_nsec;
							}
							goto LA74;
							LA76: ;
							{
								tmspec0.tv_sec = (NI)(tmspec0.tv_sec - ((NI) 1));
								diff_167625_3891511846 = (NI)(enspec0.tv_nsec - tmspec0.tv_nsec);
								tmspec0.tv_nsec = (NI)(((NI) 1000000000) - diff_167625_3891511846);
							}
							LA74: ;
							stspec0.tv_sec = b_167627_3891511846.tv_sec;
							stspec0.tv_nsec = b_167627_3891511846.tv_nsec;
						}
						LA43: ;
					}
					goto LA39;
					LA41: ;
					{
						NI32 err0;
						if (!(res0 < ((NI32) 0))) goto LA80;
						err0 = oslasterror_131619_2125978480();
						{
							NI volatile diff_167663_3891511846;
							struct timespec b_167665_3891511846;
							NI64 LOC92;
							NI64 LOC105;
							if (!(err0 == EINTR)) goto LA84;
							{
								int LOC88;
								NI32 LOC91;
								LOC88 = (int)0;
								LOC88 = clock_gettime(((clockid_t) (CLOCK_REALTIME)), (&enspec0));
								if (!(LOC88 == ((NI32) -1))) goto LA89;
								LOC91 = (NI32)0;
								LOC91 = oslasterror_131619_2125978480();
								raiseoserror_131603_2125978480(LOC91, ((NimStringDesc*) &T3891511846_11));
							}
							LA89: ;
							diff_167663_3891511846 = (NI)0;
							memset((void*)(&b_167665_3891511846), 0, sizeof(b_167665_3891511846));
							b_167665_3891511846.tv_sec = enspec0.tv_sec;
							b_167665_3891511846.tv_nsec = enspec0.tv_nsec;
							LOC92 = (NI64)0;
							LOC92 = ntDiffTime(enspec0.tv_sec, stspec0.tv_sec);
							enspec0.tv_sec = ((time_t) (LOC92));
							{
								if (!(stspec0.tv_nsec <= enspec0.tv_nsec)) goto LA95;
								enspec0.tv_nsec -= stspec0.tv_nsec;
							}
							goto LA93;
							LA95: ;
							{
								{
									NIM_BOOL LOC100;
									Valueerror3646* volatile e_167677_3891511846;
									NimStringDesc* LOC103;
									LOC100 = (NIM_BOOL)0;
									LOC100 = ntEqTime(enspec0.tv_sec, ((time_t) 0));
									if (!LOC100) goto LA101;
									e_167677_3891511846 = (Valueerror3646*)0;
									e_167677_3891511846 = (Valueerror3646*) newObj((&NTI23025), sizeof(Valueerror3646));
									(*e_167677_3891511846).Sup.Sup.m_type = (&NTI3646);
									LOC103 = (NimStringDesc*)0;
									LOC103 = (*e_167677_3891511846).Sup.message; (*e_167677_3891511846).Sup.message = copyStringRC1(((NimStringDesc*) &T3891511846_21));
									if (LOC103) nimGCunrefNoCycle(LOC103);
									raiseException((Exception*)e_167677_3891511846, "ValueError");
								}
								goto LA98;
								LA101: ;
								{
									diff_167663_3891511846 = (NI)(stspec0.tv_nsec - enspec0.tv_nsec);
									enspec0.tv_nsec = (NI)(((NI) 1000000000) - diff_167663_3891511846);
								}
								LA98: ;
							}
							LA93: ;
							LOC105 = (NI64)0;
							LOC105 = ntDiffTime(tmspec0.tv_sec, enspec0.tv_sec);
							tmspec0.tv_sec = ((time_t) (LOC105));
							{
								if (!(enspec0.tv_nsec <= tmspec0.tv_nsec)) goto LA108;
								tmspec0.tv_nsec -= enspec0.tv_nsec;
							}
							goto LA106;
							LA108: ;
							{
								tmspec0.tv_sec = (NI)(tmspec0.tv_sec - ((NI) 1));
								diff_167663_3891511846 = (NI)(enspec0.tv_nsec - tmspec0.tv_nsec);
								tmspec0.tv_nsec = (NI)(((NI) 1000000000) - diff_167663_3891511846);
							}
							LA106: ;
							stspec0.tv_sec = b_167665_3891511846.tv_sec;
							stspec0.tv_nsec = b_167665_3891511846.tv_nsec;
						}
						goto LA82;
						LA84: ;
						{
							if (!(err0 == EAGAIN)) goto LA112;
							{
								int LOC116;
								NI32 LOC119;
								LOC116 = (int)0;
								LOC116 = kill((*p0).id, SIGKILL);
								if (!(LOC116 == ((NI32) -1))) goto LA117;
								LOC119 = (NI32)0;
								LOC119 = oslasterror_131619_2125978480();
								raiseoserror_131603_2125978480(LOC119, ((NimStringDesc*) &T3891511846_11));
							}
							LA117: ;
							{
								pid_t LOC122;
								NI32 LOC125;
								LOC122 = (pid_t)0;
								LOC122 = waitpid((*p0).id, (&(*p0).exitcode), ((int) 0));
								if (!(LOC122 < ((NI) 0))) goto LA123;
								(*p0).exitcode = ((int) -3);
								LOC125 = (NI32)0;
								LOC125 = oslasterror_131619_2125978480();
								raiseoserror_131603_2125978480(LOC125, ((NimStringDesc*) &T3891511846_11));
							}
							LA123: ;
							goto LA37;
						}
						goto LA82;
						LA112: ;
						{
							raiseoserror_131603_2125978480(err0, ((NimStringDesc*) &T3891511846_11));
						}
						LA82: ;
					}
					goto LA39;
					LA80: ;
					LA39: ;
				}
			} LA37: ;
			popSafePoint();
		}
		else {
			popSafePoint();
		}
		{
			{
				int LOC131;
				NI32 LOC134;
				LOC131 = (int)0;
				LOC131 = sigprocmask(SIG_UNBLOCK, (&nmask0), (&omask0));
				if (!(LOC131 == ((NI32) -1))) goto LA132;
				LOC134 = (NI32)0;
				LOC134 = oslasterror_131619_2125978480();
				raiseoserror_131603_2125978480(LOC134, ((NimStringDesc*) &T3891511846_11));
			}
			LA132: ;
		}
		if (T3891511846_20.status != 0) reraiseException();
	}
	LA5: ;
	result0 = (NI)((NU32)(((NI) ((*p0).exitcode))) >> (NU32)(((NI) 8)));
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command0) {
	NI result0;
	int LOC1;
	result0 = (NI)0;
	LOC1 = (int)0;
	LOC1 = system(command0->data);
	result0 = ((NI) ((NI32)((NU32)(LOC1) >> (NU32)(((NI32) 8)))));
	return result0;
}

N_NIMCALL(NI, peekexitcode_164677_3891511846)(Processobj164404* p0) {
	NI result0;
	pid_t ret0;
	NIM_BOOL b0;
{	result0 = (NI)0;
	{
		if (!!(((*p0).exitcode == ((NI32) -3)))) goto LA3;
		result0 = ((NI) ((*p0).exitcode));
		goto BeforeRet;
	}
	LA3: ;
	ret0 = waitpid((*p0).id, (&(*p0).exitcode), WNOHANG);
	b0 = (ret0 == (*p0).id);
	{
		if (!b0) goto LA7;
		result0 = ((NI) -1);
	}
	LA7: ;
	{
		NIM_BOOL LOC11;
		LOC11 = (NIM_BOOL)0;
		LOC11 = WIFEXITED((*p0).exitcode);
		if (!!(LOC11)) goto LA12;
		(*p0).exitcode = ((int) -3);
		result0 = ((NI) -1);
	}
	goto LA9;
	LA12: ;
	{
		result0 = (NI)((NU32)(((NI) ((*p0).exitcode))) >> (NU32)(((NI) 8)));
	}
	LA9: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, nospcountProcessors)(void) {
	NI result0;
	result0 = (NI)0;
	result0 = ncpicountProcessors();
	return result0;
}
N_NIMCALL(void, T3891511846_22)(void* p, NI op) {
	TY165001* a;
	NI LOC1;
	a = (TY165001*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, incref_53419_1689653243)(Cell47305* c0) {
	(*c0).refcount = (NI)((NU32)((*c0).refcount) + (NU32)(((NI) 8)));
}

static N_INLINE(void, decref_53001_1689653243)(Cell47305* c0) {
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA3;
		rtladdzct_52601_1689653243(c0);
	}
	LA3: ;
}

static N_INLINE(void, asgnRef)(void** dest0, void* src0) {
	{
		Cell47305* LOC5;
		if (!!((src0 == NIM_NIL))) goto LA3;
		LOC5 = (Cell47305*)0;
		LOC5 = usrtocell_51440_1689653243(src0);
		incref_53419_1689653243(LOC5);
	}
	LA3: ;
	{
		Cell47305* LOC10;
		if (!!(((*dest0) == NIM_NIL))) goto LA8;
		LOC10 = (Cell47305*)0;
		LOC10 = usrtocell_51440_1689653243((*dest0));
		decref_53001_1689653243(LOC10);
	}
	LA8: ;
	(*dest0) = src0;
}

N_NIMCALL(NIM_BOOL, nosprunning)(Processobj164404* p0) {
	NIM_BOOL result0;
	NI ret0;
{	result0 = (NIM_BOOL)0;
	ret0 = (NI)0;
	ret0 = waitpid((*p0).id, (&(*p0).exitcode), WNOHANG);
	{
		if (!(ret0 == ((NI) 0))) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	result0 = (ret0 == (*p0).id);
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, nospclose)(Processobj164404* p0) {
	{
		if (!!(((*p0).instream == NIM_NIL))) goto LA3;
		close_157873_1780494535((*p0).instream);
	}
	LA3: ;
	{
		if (!!(((*p0).outstream == NIM_NIL))) goto LA7;
		close_157873_1780494535((*p0).outstream);
	}
	LA7: ;
	{
		if (!!(((*p0).errstream == NIM_NIL))) goto LA11;
		close_157873_1780494535((*p0).errstream);
	}
	LA11: ;
	{
		int LOC17;
		int LOC18;
		int LOC19;
		if (!!((((*p0).options &(1U<<((NU)(((Processoption164402) 4))&7U)))!=0))) goto LA15;
		LOC17 = (int)0;
		LOC17 = close((*p0).inhandle);
		LOC18 = (int)0;
		LOC18 = close((*p0).outhandle);
		LOC19 = (int)0;
		LOC19 = close((*p0).errhandle);
	}
	LA15: ;
}

N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds0, NI cmds0Len0, Processoption164402Set options_164709_3891511846, NI n0, TY276578 beforerunevent0, TY276584 afterrunevent0) {
	NI result0;
	Processoption164402Set options0;
	result0 = (NI)0;
	options0 = (options_164709_3891511846 & ~ 16);
	{
		TY165001* q0;
		NI m0;
		NI i0;
		if (!(((NI) 1) < n0)) goto LA3;
		q0 = (TY165001*)0;
		q0 = (TY165001*) newSeq((&NTI165001), ((NI) (n0)));
		m0 = ((n0 <= cmds0Len0) ? n0 : cmds0Len0);
		{
			NI i_165034_3891511846;
			NI HEX3Atmp_165352_3891511846;
			NI res_165355_3891511846;
			i_165034_3891511846 = (NI)0;
			HEX3Atmp_165352_3891511846 = (NI)0;
			HEX3Atmp_165352_3891511846 = (NI)(m0 - ((NI) 1));
			res_165355_3891511846 = ((NI) 0);
			{
				while (1) {
					TY319494 LOC12;
					if (!(res_165355_3891511846 <= HEX3Atmp_165352_3891511846)) goto LA7;
					i_165034_3891511846 = res_165355_3891511846;
					{
						if (!!((beforerunevent0.ClPrc == T3891511846_23.ClPrc && beforerunevent0.ClEnv == T3891511846_23.ClEnv))) goto LA10;
						beforerunevent0.ClEnv? beforerunevent0.ClPrc(i_165034_3891511846, beforerunevent0.ClEnv):((T3891511846_24)(beforerunevent0.ClPrc))(i_165034_3891511846);
					}
					LA10: ;
					memset((void*)LOC12, 0, sizeof(LOC12));
					asgnRef((void**) (&q0->data[i_165034_3891511846]), nospstartProcess(cmds0[i_165034_3891511846], ((NimStringDesc*) &T3891511846_11), LOC12, 0, NIM_NIL, (options0 | 4)));
					res_165355_3891511846 += ((NI) 1);
				} LA7: ;
			}
		}
		i0 = m0;
		{
			while (1) {
				if (!(i0 <= (cmds0Len0-1))) goto LA14;
				nossleep(((NI) 50));
				{
					NI r_165212_3891511846;
					NI HEX3Atmp_165361_3891511846;
					NI res_165364_3891511846;
					r_165212_3891511846 = (NI)0;
					HEX3Atmp_165361_3891511846 = (NI)0;
					HEX3Atmp_165361_3891511846 = (NI)(n0 - ((NI) 1));
					res_165364_3891511846 = ((NI) 0);
					{
						while (1) {
							if (!(res_165364_3891511846 <= HEX3Atmp_165361_3891511846)) goto LA17;
							r_165212_3891511846 = res_165364_3891511846;
							{
								NIM_BOOL LOC20;
								NI LOC23;
								TY319494 LOC36;
								LOC20 = (NIM_BOOL)0;
								LOC20 = nosprunning(q0->data[r_165212_3891511846]);
								if (!!(LOC20)) goto LA21;
								LOC23 = (NI)0;
								LOC23 = nospwaitForExit(q0->data[r_165212_3891511846], ((NI) -1));
								result0 = ((LOC23 >= result0) ? LOC23 : result0);
								{
									if (!!((afterrunevent0.ClPrc == T3891511846_25.ClPrc && afterrunevent0.ClEnv == T3891511846_25.ClEnv))) goto LA26;
									afterrunevent0.ClEnv? afterrunevent0.ClPrc(r_165212_3891511846, q0->data[r_165212_3891511846], afterrunevent0.ClEnv):((T3891511846_26)(afterrunevent0.ClPrc))(r_165212_3891511846, q0->data[r_165212_3891511846]);
								}
								LA26: ;
								{
									if (!!((q0->data[r_165212_3891511846] == NIM_NIL))) goto LA30;
									nospclose(q0->data[r_165212_3891511846]);
								}
								LA30: ;
								{
									if (!!((beforerunevent0.ClPrc == T3891511846_23.ClPrc && beforerunevent0.ClEnv == T3891511846_23.ClEnv))) goto LA34;
									beforerunevent0.ClEnv? beforerunevent0.ClPrc(i0, beforerunevent0.ClEnv):((T3891511846_27)(beforerunevent0.ClPrc))(i0);
								}
								LA34: ;
								memset((void*)LOC36, 0, sizeof(LOC36));
								asgnRef((void**) (&q0->data[r_165212_3891511846]), nospstartProcess(cmds0[i0], ((NimStringDesc*) &T3891511846_11), LOC36, 0, NIM_NIL, (options0 | 4)));
								i0 += ((NI) 1);
								{
									if (!((cmds0Len0-1) < i0)) goto LA39;
									goto LA15;
								}
								LA39: ;
							}
							LA21: ;
							res_165364_3891511846 += ((NI) 1);
						} LA17: ;
					}
				} LA15: ;
			} LA14: ;
		}
		{
			NI j_165278_3891511846;
			NI HEX3Atmp_165369_3891511846;
			NI res_165372_3891511846;
			j_165278_3891511846 = (NI)0;
			HEX3Atmp_165369_3891511846 = (NI)0;
			HEX3Atmp_165369_3891511846 = (NI)(m0 - ((NI) 1));
			res_165372_3891511846 = ((NI) 0);
			{
				while (1) {
					NI LOC44;
					if (!(res_165372_3891511846 <= HEX3Atmp_165369_3891511846)) goto LA43;
					j_165278_3891511846 = res_165372_3891511846;
					LOC44 = (NI)0;
					LOC44 = nospwaitForExit(q0->data[j_165278_3891511846], ((NI) -1));
					result0 = ((LOC44 >= result0) ? LOC44 : result0);
					{
						if (!!((afterrunevent0.ClPrc == T3891511846_25.ClPrc && afterrunevent0.ClEnv == T3891511846_25.ClEnv))) goto LA47;
						afterrunevent0.ClEnv? afterrunevent0.ClPrc(j_165278_3891511846, q0->data[j_165278_3891511846], afterrunevent0.ClEnv):((T3891511846_28)(afterrunevent0.ClPrc))(j_165278_3891511846, q0->data[j_165278_3891511846]);
					}
					LA47: ;
					{
						if (!!((q0->data[j_165278_3891511846] == NIM_NIL))) goto LA51;
						nospclose(q0->data[j_165278_3891511846]);
					}
					LA51: ;
					res_165372_3891511846 += ((NI) 1);
				} LA43: ;
			}
		}
	}
	goto LA1;
	LA3: ;
	{
		{
			NI i_165313_3891511846;
			NI HEX3Atmp_165377_3891511846;
			NI res_165380_3891511846;
			i_165313_3891511846 = (NI)0;
			HEX3Atmp_165377_3891511846 = (NI)0;
			HEX3Atmp_165377_3891511846 = (cmds0Len0-1);
			res_165380_3891511846 = ((NI) 0);
			{
				while (1) {
					Processobj164404* p0;
					TY319494 LOC61;
					NI LOC62;
					if (!(res_165380_3891511846 <= HEX3Atmp_165377_3891511846)) goto LA56;
					i_165313_3891511846 = res_165380_3891511846;
					{
						if (!!((beforerunevent0.ClPrc == T3891511846_23.ClPrc && beforerunevent0.ClEnv == T3891511846_23.ClEnv))) goto LA59;
						beforerunevent0.ClEnv? beforerunevent0.ClPrc(i_165313_3891511846, beforerunevent0.ClEnv):((T3891511846_29)(beforerunevent0.ClPrc))(i_165313_3891511846);
					}
					LA59: ;
					memset((void*)LOC61, 0, sizeof(LOC61));
					p0 = nospstartProcess(cmds0[i_165313_3891511846], ((NimStringDesc*) &T3891511846_11), LOC61, 0, NIM_NIL, (options0 | 4));
					LOC62 = (NI)0;
					LOC62 = nospwaitForExit(p0, ((NI) -1));
					result0 = ((LOC62 >= result0) ? LOC62 : result0);
					{
						if (!!((afterrunevent0.ClPrc == T3891511846_25.ClPrc && afterrunevent0.ClEnv == T3891511846_25.ClEnv))) goto LA65;
						afterrunevent0.ClEnv? afterrunevent0.ClPrc(i_165313_3891511846, p0, afterrunevent0.ClEnv):((T3891511846_30)(afterrunevent0.ClPrc))(i_165313_3891511846, p0);
					}
					LA65: ;
					nospclose(p0);
					res_165380_3891511846 += ((NI) 1);
				} LA56: ;
			}
		}
	}
	LA1: ;
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void) {
static TNimNode* T3891511846_6[9];
static TNimNode* T3891511846_7[7];
NI T3891511846_9;
static char* NIM_CONST T3891511846_8[7] = {
"poEchoCmd", 
"poUsePath", 
"poEvalCommand", 
"poStdErrToStdOut", 
"poParentStreams", 
"poInteractive", 
"poDemon"};
static TNimNode T3891511846_0[19];
NTI164404.size = sizeof(Processobj164404);
NTI164404.kind = 17;
NTI164404.base = (&NTI3608);
T3891511846_6[0] = &T3891511846_0[1];
T3891511846_0[1].kind = 1;
T3891511846_0[1].offset = offsetof(Processobj164404, inhandle);
T3891511846_0[1].typ = (&NTI13011);
T3891511846_0[1].name = "inHandle";
T3891511846_6[1] = &T3891511846_0[2];
T3891511846_0[2].kind = 1;
T3891511846_0[2].offset = offsetof(Processobj164404, outhandle);
T3891511846_0[2].typ = (&NTI13011);
T3891511846_0[2].name = "outHandle";
T3891511846_6[2] = &T3891511846_0[3];
T3891511846_0[3].kind = 1;
T3891511846_0[3].offset = offsetof(Processobj164404, errhandle);
T3891511846_0[3].typ = (&NTI13011);
T3891511846_0[3].name = "errHandle";
T3891511846_6[3] = &T3891511846_0[4];
T3891511846_0[4].kind = 1;
T3891511846_0[4].offset = offsetof(Processobj164404, instream);
T3891511846_0[4].typ = (&NTI157816);
T3891511846_0[4].name = "inStream";
T3891511846_6[4] = &T3891511846_0[5];
T3891511846_0[5].kind = 1;
T3891511846_0[5].offset = offsetof(Processobj164404, outstream);
T3891511846_0[5].typ = (&NTI157816);
T3891511846_0[5].name = "outStream";
T3891511846_6[5] = &T3891511846_0[6];
T3891511846_0[6].kind = 1;
T3891511846_0[6].offset = offsetof(Processobj164404, errstream);
T3891511846_0[6].typ = (&NTI157816);
T3891511846_0[6].name = "errStream";
T3891511846_6[6] = &T3891511846_0[7];
T3891511846_0[7].kind = 1;
T3891511846_0[7].offset = offsetof(Processobj164404, id);
T3891511846_0[7].typ = (&NTI120676);
T3891511846_0[7].name = "id";
T3891511846_6[7] = &T3891511846_0[8];
T3891511846_0[8].kind = 1;
T3891511846_0[8].offset = offsetof(Processobj164404, exitcode);
T3891511846_0[8].typ = (&NTI7408);
T3891511846_0[8].name = "exitCode";
T3891511846_6[8] = &T3891511846_0[9];
NTI164402.size = sizeof(Processoption164402);
NTI164402.kind = 14;
NTI164402.base = 0;
NTI164402.flags = 3;
for (T3891511846_9 = 0; T3891511846_9 < 7; T3891511846_9++) {
T3891511846_0[T3891511846_9+10].kind = 1;
T3891511846_0[T3891511846_9+10].offset = T3891511846_9;
T3891511846_0[T3891511846_9+10].name = T3891511846_8[T3891511846_9];
T3891511846_7[T3891511846_9] = &T3891511846_0[T3891511846_9+10];
}
T3891511846_0[17].len = 7; T3891511846_0[17].kind = 2; T3891511846_0[17].sons = &T3891511846_7[0];
NTI164402.node = &T3891511846_0[17];
NTI164628.size = sizeof(Processoption164402Set);
NTI164628.kind = 19;
NTI164628.base = (&NTI164402);
NTI164628.flags = 3;
T3891511846_0[18].len = 0; T3891511846_0[18].kind = 0;
NTI164628.node = &T3891511846_0[18];
T3891511846_0[9].kind = 1;
T3891511846_0[9].offset = offsetof(Processobj164404, options);
T3891511846_0[9].typ = (&NTI164628);
T3891511846_0[9].name = "options";
T3891511846_0[0].len = 9; T3891511846_0[0].kind = 2; T3891511846_0[0].sons = &T3891511846_6[0];
NTI164404.node = &T3891511846_0[0];
NTI164406.size = sizeof(Processobj164404*);
NTI164406.kind = 22;
NTI164406.base = (&NTI164404);
NTI164406.marker = T3891511846_10;
NTI165001.size = sizeof(TY165001*);
NTI165001.kind = 24;
NTI165001.base = (&NTI164406);
NTI165001.marker = T3891511846_22;
}

