/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR TY213031[81];
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, hexchar_213091)(NIM_CHAR c, NI* xi);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, encodevintaux_213269)(NI x, NimStringDesc** result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, encodevbiggestintaux_213230)(NI64 x, NimStringDesc** result);
STRING_LITERAL(TMP1402, "", 0);
STRING_LITERAL(TMP1423, "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", 62);
STRING_LITERAL(TMP3609, "NAN", 3);
STRING_LITERAL(TMP3610, "0.0", 3);
STRING_LITERAL(TMP3611, "INF", 3);
STRING_LITERAL(TMP3612, "-INF", 4);

N_NIMCALL(NI, decodevint_213351)(NCSTRING s, NI* pos) {
	NI result;
	NI i_213358;
	NI sign_213360;
	result = 0;
	i_213358 = (*pos);
	sign_213360 = ((NI) -1);
	{
		if (!((NU8)(s[i_213358]) == (NU8)(45))) goto LA3;
		i_213358 += ((NI) 1);
		sign_213360 = ((NI) 1);
	}
	LA3: ;
	result = ((NI) 0);
	{
		while (1) {
			switch (((NU8)(s[i_213358]))) {
			case 48 ... 57:
			{
				result = (NI64)((NI64)(result * ((NI) 190)) - ((NI) ((NI64)(((NI) (((NU8)(s[i_213358])))) - ((NI) 48)))));
			}
			break;
			case 97 ... 122:
			{
				result = (NI64)((NI64)(result * ((NI) 190)) - ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(s[i_213358])))) - ((NI) 97)))) + ((NI) 10)))));
			}
			break;
			case 65 ... 90:
			{
				result = (NI64)((NI64)(result * ((NI) 190)) - ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(s[i_213358])))) - ((NI) 65)))) + ((NI) 36)))));
			}
			break;
			case 128 ... 255:
			{
				result = (NI64)((NI64)(result * ((NI) 190)) - ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(s[i_213358])))) - ((NI) 128)))) + ((NI) 62)))));
			}
			break;
			default:
			{
				goto LA5;
			}
			break;
			}
			i_213358 += ((NI) 1);
		}
	} LA5: ;
	result = (NI)((NU64)((NI64)(result * sign_213360)) - (NU64)(((NI) 5)));
	(*pos) = i_213358;
	return result;
}

N_NIMCALL(void, hexchar_213091)(NIM_CHAR c, NI* xi) {
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(((NI) 4))) | ((NI) ((NI64)(((NI) (((NU8)(c)))) - ((NI) 48)))));
	}
	break;
	case 97 ... 102:
	{
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(((NI) 4))) | ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(c)))) - ((NI) 97)))) + ((NI) 10)))));
	}
	break;
	case 65 ... 70:
	{
		(*xi) = (NI)((NI)((NU64)((*xi)) << (NU64)(((NI) 4))) | ((NI) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(c)))) - ((NI) 65)))) + ((NI) 10)))));
	}
	break;
	default:
	{
	}
	break;
	}
}

N_NIMCALL(NimStringDesc*, decodestr_213157)(NCSTRING s, NI* pos) {
	NimStringDesc* result;
	NI i;
	result = 0;
	i = (*pos);
	result = copyString(((NimStringDesc*) &TMP1402));
	{
		while (1) {
			switch (((NU8)(s[i]))) {
			case 92:
			{
				NI xi;
				i += ((NI) 3);
				xi = ((NI) 0);
				hexchar_213091(s[(NI64)(i - ((NI) 2))], (&xi));
				hexchar_213091(s[(NI64)(i - ((NI) 1))], (&xi));
				result = addChar(result, ((NIM_CHAR) (((NI) (xi)))));
			}
			break;
			case 97 ... 122:
			case 65 ... 90:
			case 48 ... 57:
			case 95:
			{
				result = addChar(result, s[i]);
				i += ((NI) 1);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	(*pos) = i;
	return result;
}

N_NIMCALL(void, encodevintaux_213269)(NI x, NimStringDesc** result) {
	NIM_CHAR d_213275;
	NI v_213277;
	NI rem_213279;
	NI idx_213281;
	d_213275 = 0;
	v_213277 = x;
	rem_213279 = (NI64)(v_213277 % ((NI) 190));
	{
		if (!(((NI) (rem_213279)) < ((NI) 0))) goto LA3;
		(*result) = addChar((*result), 45);
		v_213277 = ((NI64)-((NI64)(v_213277 / ((NI) 190))));
		rem_213279 = ((NI64)-(((NI) (rem_213279))));
	}
	goto LA1;
	LA3: ;
	{
		v_213277 = (NI64)(v_213277 / ((NI) 190));
	}
	LA1: ;
	idx_213281 = ((NI) (rem_213279));
	{
		if (!(idx_213281 < ((NI) 62))) goto LA8;
		d_213275 = ((NimStringDesc*) &TMP1423)->data[idx_213281];
	}
	goto LA6;
	LA8: ;
	{
		d_213275 = ((NIM_CHAR) (((NI) ((NI64)((NI64)(idx_213281 - ((NI) 62)) + ((NI) 128))))));
	}
	LA6: ;
	{
		if (!!((v_213277 == ((NI) 0)))) goto LA13;
		encodevintaux_213269(v_213277, result);
	}
	LA13: ;
	(*result) = addChar((*result), d_213275);
}

N_NIMCALL(void, encodevint_213296)(NI x, NimStringDesc** result) {
	encodevintaux_213269((NI)((NU64)(x) + (NU64)(((NI) 5))), result);
}

N_NIMCALL(NI64, decodevbiggestint_213512)(NCSTRING s, NI* pos) {
	NI64 result;
	NI i_213519;
	NI sign_213521;
	result = 0;
	i_213519 = (*pos);
	sign_213521 = ((NI) -1);
	{
		if (!((NU8)(s[i_213519]) == (NU8)(45))) goto LA3;
		i_213519 += ((NI) 1);
		sign_213521 = ((NI) 1);
	}
	LA3: ;
	result = IL64(0);
	{
		while (1) {
			switch (((NU8)(s[i_213519]))) {
			case 48 ... 57:
			{
				result = (NI64)((NI64)(result * IL64(190)) - ((NI64) ((NI64)(((NI) (((NU8)(s[i_213519])))) - ((NI) 48)))));
			}
			break;
			case 97 ... 122:
			{
				result = (NI64)((NI64)(result * IL64(190)) - ((NI64) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(s[i_213519])))) - ((NI) 97)))) + ((NI) 10)))));
			}
			break;
			case 65 ... 90:
			{
				result = (NI64)((NI64)(result * IL64(190)) - ((NI64) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(s[i_213519])))) - ((NI) 65)))) + ((NI) 36)))));
			}
			break;
			case 128 ... 255:
			{
				result = (NI64)((NI64)(result * IL64(190)) - ((NI64) ((NI64)(((NI) ((NI64)(((NI) (((NU8)(s[i_213519])))) - ((NI) 128)))) + ((NI) 62)))));
			}
			break;
			default:
			{
				goto LA5;
			}
			break;
			}
			i_213519 += ((NI) 1);
		}
	} LA5: ;
	result = (NI64)((NU64)((NI64)(result * ((NI64) (sign_213521)))) - (NU64)(IL64(5)));
	(*pos) = i_213519;
	return result;
}

N_NIMCALL(NimStringDesc*, tostrmaxprecision_213024)(NF f) {
	NimStringDesc* result;
	result = 0;
	{
		if (!!((f == f))) goto LA3;
		result = copyString(((NimStringDesc*) &TMP3609));
	}
	goto LA1;
	LA3: ;
	{
		if (!(f == 0.0)) goto LA6;
		result = copyString(((NimStringDesc*) &TMP3610));
	}
	goto LA1;
	LA6: ;
	{
		if (!(f == ((NF)(5.0000000000000000e-01) * (NF)(f)))) goto LA9;
		{
			if (!(0.0 < f)) goto LA13;
			result = copyString(((NimStringDesc*) &TMP3611));
		}
		goto LA11;
		LA13: ;
		{
			result = copyString(((NimStringDesc*) &TMP3612));
		}
		LA11: ;
	}
	goto LA1;
	LA9: ;
	{
		TY213031 buf;
		memset((void*)buf, 0, sizeof(buf));
		sprintf(((NCSTRING) (buf)), "%#.16e", f);
		result = cstrToNimstr(((NCSTRING) (buf)));
	}
	LA1: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, encodestr_213042)(NimStringDesc* s, NimStringDesc** result) {
	{
		NI i_213059;
		NI HEX3Atmp_213069;
		NI res_213072;
		i_213059 = 0;
		HEX3Atmp_213069 = 0;
		HEX3Atmp_213069 = (NI64)(s->Sup.len - ((NI) 1));
		res_213072 = ((NI) 0);
		{
			while (1) {
				if (!(res_213072 <= HEX3Atmp_213069)) goto LA3;
				i_213059 = res_213072;
				switch (((NU8)(s->data[i_213059]))) {
				case 97 ... 122:
				case 65 ... 90:
				case 48 ... 57:
				case 95:
				{
					(*result) = addChar((*result), s->data[i_213059]);
				}
				break;
				default:
				{
					NimStringDesc* LOC6;
					NimStringDesc* LOC7;
					LOC6 = 0;
					LOC7 = 0;
					LOC7 = nsuToHex(((NI64) (((NU8)(s->data[i_213059])))), ((NI) 2));
					LOC6 = rawNewString(LOC7->Sup.len + 1);
appendChar(LOC6, 92);
appendString(LOC6, LOC7);
					(*result) = resizeString((*result), LOC6->Sup.len + 0);
appendString((*result), LOC6);
				}
				break;
				}
				res_213072 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, encodevbiggestintaux_213230)(NI64 x, NimStringDesc** result) {
	NIM_CHAR d_213236;
	NI64 v_213238;
	NI64 rem_213240;
	NI idx_213242;
	d_213236 = 0;
	v_213238 = x;
	rem_213240 = (NI64)(v_213238 % IL64(190));
	{
		if (!(((NI) (rem_213240)) < ((NI) 0))) goto LA3;
		(*result) = addChar((*result), 45);
		v_213238 = -((NI64)(v_213238 / IL64(190)));
		rem_213240 = -(((NI64) (rem_213240)));
	}
	goto LA1;
	LA3: ;
	{
		v_213238 = (NI64)(v_213238 / IL64(190));
	}
	LA1: ;
	idx_213242 = ((NI) (rem_213240));
	{
		if (!(idx_213242 < ((NI) 62))) goto LA8;
		d_213236 = ((NimStringDesc*) &TMP1423)->data[idx_213242];
	}
	goto LA6;
	LA8: ;
	{
		d_213236 = ((NIM_CHAR) (((NI) ((NI64)((NI64)(idx_213242 - ((NI) 62)) + ((NI) 128))))));
	}
	LA6: ;
	{
		if (!!((v_213238 == IL64(0)))) goto LA13;
		encodevbiggestintaux_213230(v_213238, result);
	}
	LA13: ;
	(*result) = addChar((*result), d_213236);
}

N_NIMCALL(void, encodevbiggestint_213258)(NI64 x, NimStringDesc** result) {
	encodevbiggestintaux_213230((NI64)((NU64)(x) + (NU64)(IL64(5))), result);
}
NIM_EXTERNC N_NOINLINE(void, compiler_rodutilsInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, compiler_rodutilsDatInit)(void) {
}

