/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct tnode191813 tnode191813;
typedef struct ttype191847 ttype191847;
typedef struct tlineinfo166527 tlineinfo166527;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tsym191843 tsym191843;
typedef struct tident170019 tident170019;
typedef struct tnodeseq191807 tnodeseq191807;
typedef struct tinfocpu145453 tinfocpu145453;
typedef struct tidtable191859 tidtable191859;
typedef struct tidpairseq191857 tidpairseq191857;
typedef struct tidpair191855 tidpair191855;
typedef struct tidobj170013 tidobj170013;
typedef struct TNimObject TNimObject;
typedef struct tcell41890 tcell41890;
typedef struct TNimType TNimType;
typedef struct tcellseq41906 tcellseq41906;
typedef struct tgcheap43816 tgcheap43816;
typedef struct tcellset41902 tcellset41902;
typedef struct tpagedesc41898 tpagedesc41898;
typedef struct tmemregion24210 tmemregion24210;
typedef struct tsmallchunk23438 tsmallchunk23438;
typedef struct tllchunk24204 tllchunk24204;
typedef struct tbigchunk23440 tbigchunk23440;
typedef struct tintset23415 tintset23415;
typedef struct ttrunk23411 ttrunk23411;
typedef struct tavlnode24208 tavlnode24208;
typedef struct tgcstat43814 tgcstat43814;
typedef struct TNimNode TNimNode;
typedef struct ttypeseq191845 ttypeseq191845;
typedef struct tloc191827 tloc191827;
typedef struct trope148007 trope148007;
typedef struct tscope191837 tscope191837;
typedef struct TY191943 TY191943;
typedef struct tinstantiation191833 tinstantiation191833;
typedef struct tstrtable191817 tstrtable191817;
typedef struct tsymseq191815 tsymseq191815;
typedef struct tlib191831 tlib191831;
typedef struct tbasechunk23436 tbasechunk23436;
typedef struct tfreecell23428 tfreecell23428;
typedef struct TY191932 TY191932;
typedef struct tlistentry119017 tlistentry119017;
struct  tlineinfo166527  {
NI16 Line;
NI16 Col;
NI32 Fileindex;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tnode191813  {
ttype191847* Typ;
tlineinfo166527 Info;
NU16 Flags;
NU8 Kind;
union {
struct {NI64 Intval;
} S1;
struct {NF Floatval;
} S2;
struct {NimStringDesc* Strval;
} S3;
struct {tsym191843* Sym;
} S4;
struct {tident170019* Ident;
} S5;
struct {tnodeseq191807* Sons;
} S6;
} kindU;
NimStringDesc* Comment;
};
typedef NU8 TY192025[20];
struct tinfocpu145453 {
NimStringDesc* Field0;
NI Field1;
NU8 Field2;
NI Field3;
NI Field4;
};
typedef tinfocpu145453 TY145469[14];
struct  tidpair191855  {
tidobj170013* Key;
TNimObject* Val;
};
struct  tidtable191859  {
NI Counter;
tidpairseq191857* Data;
};
typedef tidtable191859 TY469221[62];
typedef ttype191847* TY246045[62];
struct  tcell41890  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41906  {
NI Len;
NI Cap;
tcell41890** D;
};
struct  tcellset41902  {
NI Counter;
NI Max;
tpagedesc41898* Head;
tpagedesc41898** Data;
};
typedef tsmallchunk23438* TY24222[512];
typedef ttrunk23411* ttrunkbuckets23413[256];
struct  tintset23415  {
ttrunkbuckets23413 Data;
};
struct  tmemregion24210  {
NI Minlargeobj;
NI Maxlargeobj;
TY24222 Freesmallchunks;
tllchunk24204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk23440* Freechunkslist;
tintset23415 Chunkstarts;
tavlnode24208* Root;
tavlnode24208* Deleted;
tavlnode24208* Last;
tavlnode24208* Freeavlnodes;
};
struct  tgcstat43814  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43816  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41906 Zct;
tcellseq41906 Decstack;
tcellset41902 Cycleroots;
tcellseq41906 Tempstack;
NI Recgclock;
tmemregion24210 Region;
tgcstat43814 Stat;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  tidobj170013  {
  TNimObject Sup;
NI Id;
};
struct  tloc191827  {
NU8 K;
NU8 S;
NU8 Flags;
ttype191847* T;
trope148007* R;
trope148007* Heaproot;
NI A;
};
struct  ttype191847  {
  tidobj170013 Sup;
NU8 Kind;
NU8 Callconv;
NU32 Flags;
ttypeseq191845* Sons;
tnode191813* N;
tsym191843* Destructor;
tsym191843* Owner;
tsym191843* Sym;
NI64 Size;
NI Align;
tloc191827 Loc;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tstrtable191817  {
NI Counter;
tsymseq191815* Data;
};
struct  tsym191843  {
  tidobj170013 Sup;
NU8 Kind;
union {
struct {ttypeseq191845* Typeinstcache;
tscope191837* Typscope;
} S1;
struct {TY191943* Procinstcache;
tscope191837* Scope;
} S2;
struct {TY191943* Usedgenerics;
tstrtable191817 Tab;
} S3;
} kindU;
NU16 Magic;
ttype191847* Typ;
tident170019* Name;
tlineinfo166527 Info;
tsym191843* Owner;
NU32 Flags;
tnode191813* Ast;
NU32 Options;
NI Position;
NI Offset;
tloc191827 Loc;
tlib191831* Annex;
tnode191813* Constraint;
};
struct  tident170019  {
  tidobj170013 Sup;
NimStringDesc* S;
tident170019* Next;
NI H;
};
typedef NI TY23418[16];
struct  tpagedesc41898  {
tpagedesc41898* Next;
NI Key;
TY23418 Bits;
};
struct  tbasechunk23436  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk23438  {
  tbasechunk23436 Sup;
tsmallchunk23438* Next;
tsmallchunk23438* Prev;
tfreecell23428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk24204  {
NI Size;
NI Acc;
tllchunk24204* Next;
};
struct  tbigchunk23440  {
  tbasechunk23436 Sup;
tbigchunk23440* Next;
tbigchunk23440* Prev;
NI Align;
NF Data;
};
struct  ttrunk23411  {
ttrunk23411* Next;
NI Key;
TY23418 Bits;
};
typedef tavlnode24208* TY24214[2];
struct  tavlnode24208  {
TY24214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  trope148007  {
  TNimObject Sup;
trope148007* Left;
trope148007* Right;
NI Length;
NimStringDesc* Data;
};
struct  tscope191837  {
NI Depthlevel;
tstrtable191817 Symbols;
tnodeseq191807* Usingsyms;
tscope191837* Parent;
};
struct  tinstantiation191833  {
tsym191843* Sym;
ttypeseq191845* Concretetypes;
TY191932* Usedby;
};
struct  tlistentry119017  {
  TNimObject Sup;
tlistentry119017* Prev;
tlistentry119017* Next;
};
struct  tlib191831  {
  tlistentry119017 Sup;
NU8 Kind;
NIM_BOOL Generated;
NIM_BOOL Isoverriden;
trope148007* Name;
tnode191813* Path;
};
struct  tfreecell23428  {
tfreecell23428* Next;
NI Zerofield;
};
struct tnodeseq191807 {
  TGenericSeq Sup;
  tnode191813* data[SEQ_DECL_SIZE];
};
struct tidpairseq191857 {
  TGenericSeq Sup;
  tidpair191855 data[SEQ_DECL_SIZE];
};
struct ttypeseq191845 {
  TGenericSeq Sup;
  ttype191847* data[SEQ_DECL_SIZE];
};
struct TY191943 {
  TGenericSeq Sup;
  tinstantiation191833* data[SEQ_DECL_SIZE];
};
struct tsymseq191815 {
  TGenericSeq Sup;
  tsym191843* data[SEQ_DECL_SIZE];
};
struct TY191932 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(tnode191813*, getpragmastmt_469012)(tnode191813* n, NU8 w);
static N_INLINE(NI, len_192274)(tnode191813* n);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tnode191813*, HEX5BHEX5D_192711)(tnode191813* n, NI i);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NU8, whichpragma_226161)(tnode191813* n);
N_NIMCALL(NIM_BOOL, stmtscontainpragma_469099)(tnode191813* n, NU8 w);
N_NIMCALL(NI64, hashstring_469123)(NimStringDesc* s);
N_NIMCALL(void, inittypetables_469232)(void);
N_NIMCALL(void, initidtable_192130)(tidtable191859* x);
N_NIMCALL(void, resetcaches_469288)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell41890*, usrtocell_45243)(void* usr);
static N_INLINE(void, rtladdzct_46802)(tcell41890* c);
N_NOINLINE(void, addzct_45218)(tcellseq41906* s, tcell41890* c);
N_NIMCALL(ttype191847*, getuniquetype_469401)(ttype191847* key);
N_NIMCALL(void, internalerror_168606)(NimStringDesc* errmsg);
static N_INLINE(ttype191847*, lastson_192203)(ttype191847* n);
static N_INLINE(NI, sonslen_192195)(ttype191847* n);
N_NIMCALL(NIM_BOOL, idtablehasobjectaskey_200154)(tidtable191859 t, tidobj170013* key);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NIM_BOOL, samebackendtype_234539)(ttype191847* x, ttype191847* y);
N_NIMCALL(void, idtableput_200147)(tidtable191859* t, tidobj170013* key, TNimObject* val);
N_NIMCALL(TNimObject*, idtableget_200137)(tidtable191859 t, tidobj170013* key);
N_NIMCALL(NIM_BOOL, sametype_232139)(ttype191847* a, ttype191847* b, NU8 flags);
N_NIMCALL(TNimObject*, tablegettype_469611)(tidtable191859 tab, ttype191847* key);
N_NIMCALL(NimStringDesc*, makesinglelinecstring_469672)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, tocchar_166645)(NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, failedassertimpl_80421)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, mangle_469684)(NimStringDesc* name);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
N_NIMCALL(trope148007*, makellvmstring_469723)(NimStringDesc* s);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, app_148040)(trope148007** a, trope148007* b);
N_NIMCALL(trope148007*, torope_148058)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
static NIM_CONST TY192025 TMP6194 = {
0xEC, 0xFF, 0x7F, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP6195, "sons", 4);
extern NIM_CONST TY145469 cpu_145468;
STRING_LITERAL(TMP6198, "GetUniqueType", 13);
STRING_LITERAL(TMP6200, "\"", 1);
STRING_LITERAL(TMP6201, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TMP6202, "", 0);
STRING_LITERAL(TMP6203, "N", 1);
STRING_LITERAL(TMP6204, "HEX", 3);
STRING_LITERAL(TMP6206, "c\"", 2);
STRING_LITERAL(TMP6210, "\\00\"", 4);
extern TFrame* frameptr_13238;
extern NU8 targetcpu_145573;
TY469221 gtypetable_469224;
TY246045 gcanonicaltypes_469228;
extern tgcheap43816 gch_43844;
extern TNimType NTI191847; /* TType */

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

static N_INLINE(NI, len_192274)(tnode191813* n) {
	NI result;
	nimfr("len", "ast.nim")
	result = 0;
	nimln(957, "ast.nim");
	{
		nimln(957, "ast.nim");
		if (((TMP6194[(*n).Kind/8] &(1<<((*n).Kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP6195));
		if (!(*n).kindU.S6.Sons == 0) goto LA3;
		nimln(957, "ast.nim");
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		nimln(958, "ast.nim");
		nimln(958, "ast.nim");
		if (((TMP6194[(*n).Kind/8] &(1<<((*n).Kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP6195));
		result = (*n).kindU.S6.Sons->Sup.len;
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(tnode191813*, HEX5BHEX5D_192711)(tnode191813* n, NI i) {
	tnode191813* result;
	nimfr("[]", "ast.nim")
	result = 0;
	nimln(971, "ast.nim");
	if (((TMP6194[(*n).Kind/8] &(1<<((*n).Kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP6195));
	if ((NU)(i) >= (NU)((*n).kindU.S6.Sons->Sup.len)) raiseIndexError();
	result = (*n).kindU.S6.Sons->data[i];
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(tnode191813*, getpragmastmt_469012)(tnode191813* n, NU8 w) {
	tnode191813* result;
	nimfr("getPragmaStmt", "ccgutils.nim")
	result = 0;
	nimln(17, "ccgutils.nim");
	switch ((*n).Kind) {
	case ((NU8) 114):
	{
		NI i_469038;
		NI HEX3Atmp_469087;
		NI LOC2;
		NI res_469089;
		i_469038 = 0;
		HEX3Atmp_469087 = 0;
		nimln(19, "ccgutils.nim");
		nimln(19, "ccgutils.nim");
		nimln(19, "ccgutils.nim");
		LOC2 = 0;
		LOC2 = len_192274(n);
		HEX3Atmp_469087 = subInt(LOC2, 1);
		nimln(1458, "system.nim");
		res_469089 = 0;
		nimln(1459, "system.nim");
		while (1) {
			tnode191813* LOC4;
			nimln(1459, "system.nim");
			if (!(res_469089 <= HEX3Atmp_469087)) goto LA3;
			nimln(1458, "system.nim");
			i_469038 = res_469089;
			nimln(20, "ccgutils.nim");
			nimln(20, "ccgutils.nim");
			LOC4 = 0;
			LOC4 = HEX5BHEX5D_192711(n, i_469038);
			result = getpragmastmt_469012(LOC4, w);
			nimln(21, "ccgutils.nim");
			{
				nimln(21, "ccgutils.nim");
				nimln(21, "ccgutils.nim");
				if (!!((result == NIM_NIL))) goto LA7;
				nimln(21, "ccgutils.nim");
				goto LA3;
			}
			LA7: ;
			nimln(1461, "system.nim");
			res_469089 = addInt(res_469089, 1);
		} LA3: ;
	}
	break;
	case ((NU8) 90):
	{
		NI i_469077;
		NI HEX3Atmp_469091;
		NI LOC10;
		NI res_469093;
		i_469077 = 0;
		HEX3Atmp_469091 = 0;
		nimln(23, "ccgutils.nim");
		nimln(23, "ccgutils.nim");
		nimln(23, "ccgutils.nim");
		LOC10 = 0;
		LOC10 = len_192274(n);
		HEX3Atmp_469091 = subInt(LOC10, 1);
		nimln(1458, "system.nim");
		res_469093 = 0;
		nimln(1459, "system.nim");
		while (1) {
			nimln(1459, "system.nim");
			if (!(res_469093 <= HEX3Atmp_469091)) goto LA11;
			nimln(1458, "system.nim");
			i_469077 = res_469093;
			nimln(24, "ccgutils.nim");
			{
				tnode191813* LOC14;
				NU8 LOC15;
				nimln(24, "ccgutils.nim");
				nimln(24, "ccgutils.nim");
				nimln(24, "ccgutils.nim");
				LOC14 = 0;
				LOC14 = HEX5BHEX5D_192711(n, i_469077);
				LOC15 = 0;
				LOC15 = whichpragma_226161(LOC14);
				if (!(LOC15 == w)) goto LA16;
				nimln(24, "ccgutils.nim");
				nimln(24, "ccgutils.nim");
				result = HEX5BHEX5D_192711(n, i_469077);
				goto BeforeRet;
			}
			LA16: ;
			nimln(1461, "system.nim");
			res_469093 = addInt(res_469093, 1);
		} LA11: ;
	}
	break;
	default:
	{
	}
	break;
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, stmtscontainpragma_469099)(tnode191813* n, NU8 w) {
	NIM_BOOL result;
	tnode191813* LOC1;
	nimfr("stmtsContainPragma", "ccgutils.nim")
	result = 0;
	nimln(28, "ccgutils.nim");
	nimln(28, "ccgutils.nim");
	nimln(28, "ccgutils.nim");
	nimln(28, "ccgutils.nim");
	LOC1 = 0;
	LOC1 = getpragmastmt_469012(n, w);
	result = !((LOC1 == NIM_NIL));
	popFrame();
	return result;
}

N_NIMCALL(NI64, hashstring_469123)(NimStringDesc* s) {
	NI64 result;
	nimfr("hashString", "ccgutils.nim")
	result = 0;
	nimln(32, "ccgutils.nim");
	{
		NI64 b;
		NI i_469140;
		NI HEX3Atmp_469208;
		NI TMP6196;
		NI res_469210;
		nimln(32, "ccgutils.nim");
		if (targetcpu_145573 < 1 || targetcpu_145573 > 14) raiseIndexError();
		if (!(cpu_145468[(targetcpu_145573)- 1].Field4 == 64)) goto LA3;
		nimln(35, "ccgutils.nim");
		b = 0;
		i_469140 = 0;
		HEX3Atmp_469208 = 0;
		nimln(36, "ccgutils.nim");
		nimln(36, "ccgutils.nim");
		nimln(36, "ccgutils.nim");
		TMP6196 = subInt(s->Sup.len, 1);
		HEX3Atmp_469208 = (NI32)(TMP6196);
		nimln(1451, "system.nim");
		res_469210 = 0;
		nimln(1452, "system.nim");
		while (1) {
			nimln(1452, "system.nim");
			if (!(res_469210 <= HEX3Atmp_469208)) goto LA5;
			nimln(1451, "system.nim");
			i_469140 = res_469210;
			nimln(37, "ccgutils.nim");
			nimln(37, "ccgutils.nim");
			nimln(37, "ccgutils.nim");
			if ((NU)(i_469140) > (NU)(s->Sup.len)) raiseIndexError();
			b = (NI64)((NU64)(b) + (NU64)(((NI64) (((NU8)(s->data[i_469140]))))));
			nimln(38, "ccgutils.nim");
			nimln(38, "ccgutils.nim");
			nimln(38, "ccgutils.nim");
			b = (NI64)((NU64)(b) + (NU64)((NI64)((NU64)(b) << (NU64)(10))));
			nimln(39, "ccgutils.nim");
			nimln(39, "ccgutils.nim");
			nimln(39, "ccgutils.nim");
			b = (NI64)(b ^ (NI64)((NU64)(b) >> (NU64)(6)));
			nimln(1454, "system.nim");
			res_469210 = addInt(res_469210, 1);
		} LA5: ;
		nimln(40, "ccgutils.nim");
		nimln(40, "ccgutils.nim");
		nimln(40, "ccgutils.nim");
		b = (NI64)((NU64)(b) + (NU64)((NI64)((NU64)(b) << (NU64)(3))));
		nimln(41, "ccgutils.nim");
		nimln(41, "ccgutils.nim");
		nimln(41, "ccgutils.nim");
		b = (NI64)(b ^ (NI64)((NU64)(b) >> (NU64)(11)));
		nimln(42, "ccgutils.nim");
		nimln(42, "ccgutils.nim");
		nimln(42, "ccgutils.nim");
		b = (NI64)((NU64)(b) + (NU64)((NI64)((NU64)(b) << (NU64)(15))));
		nimln(43, "ccgutils.nim");
		result = b;
	}
	goto LA1;
	LA3: ;
	{
		NI32 a;
		NI i_469162;
		NI HEX3Atmp_469213;
		NI TMP6197;
		NI res_469215;
		nimln(45, "ccgutils.nim");
		a = ((NI32) 0);
		i_469162 = 0;
		HEX3Atmp_469213 = 0;
		nimln(46, "ccgutils.nim");
		nimln(46, "ccgutils.nim");
		nimln(46, "ccgutils.nim");
		TMP6197 = subInt(s->Sup.len, 1);
		HEX3Atmp_469213 = (NI32)(TMP6197);
		nimln(1451, "system.nim");
		res_469215 = 0;
		nimln(1452, "system.nim");
		while (1) {
			nimln(1452, "system.nim");
			if (!(res_469215 <= HEX3Atmp_469213)) goto LA7;
			nimln(1451, "system.nim");
			i_469162 = res_469215;
			nimln(47, "ccgutils.nim");
			nimln(47, "ccgutils.nim");
			nimln(47, "ccgutils.nim");
			if ((NU)(i_469162) > (NU)(s->Sup.len)) raiseIndexError();
			a = (NI32)((NU32)(a) + (NU32)(((NI32) (((NU8)(s->data[i_469162]))))));
			nimln(48, "ccgutils.nim");
			nimln(48, "ccgutils.nim");
			nimln(48, "ccgutils.nim");
			a = (NI32)((NU32)(a) + (NU32)((NI32)((NU32)(a) << (NU32)(((NI32) 10)))));
			nimln(49, "ccgutils.nim");
			nimln(49, "ccgutils.nim");
			nimln(49, "ccgutils.nim");
			a = (NI32)(a ^ (NI32)((NU32)(a) >> (NU32)(((NI32) 6))));
			nimln(1454, "system.nim");
			res_469215 = addInt(res_469215, 1);
		} LA7: ;
		nimln(50, "ccgutils.nim");
		nimln(50, "ccgutils.nim");
		nimln(50, "ccgutils.nim");
		a = (NI32)((NU32)(a) + (NU32)((NI32)((NU32)(a) << (NU32)(((NI32) 3)))));
		nimln(51, "ccgutils.nim");
		nimln(51, "ccgutils.nim");
		nimln(51, "ccgutils.nim");
		a = (NI32)(a ^ (NI32)((NU32)(a) >> (NU32)(((NI32) 11))));
		nimln(52, "ccgutils.nim");
		nimln(52, "ccgutils.nim");
		nimln(52, "ccgutils.nim");
		a = (NI32)((NU32)(a) + (NU32)((NI32)((NU32)(a) << (NU32)(((NI32) 15)))));
		nimln(53, "ccgutils.nim");
		result = ((NI64) (a));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, inittypetables_469232)(void) {
	NU8 i_469278;
	NU8 res_469283;
	nimfr("initTypeTables", "ccgutils.nim")
	i_469278 = 0;
	nimln(1451, "system.nim");
	res_469283 = ((NU8) 0);
	nimln(1452, "system.nim");
	while (1) {
		nimln(1452, "system.nim");
		if (!(res_469283 <= ((NU8) 61))) goto LA1;
		nimln(1451, "system.nim");
		i_469278 = res_469283;
		nimln(60, "ccgutils.nim");
		initidtable_192130(&gtypetable_469224[(i_469278)- 0]);
		nimln(1454, "system.nim");
		res_469283 = addInt(res_469283, 1);
	} LA1: ;
	popFrame();
}

static N_INLINE(tcell41890*, usrtocell_45243)(void* usr) {
	tcell41890* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41890*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell41890))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46802)(tcell41890* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_45218(&gch_43844.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41890* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_45243(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41890* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_45243((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46802(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, resetcaches_469288)(void) {
	NU8 i_469300;
	NU8 res_469302;
	nimfr("resetCaches", "ccgutils.nim")
	nimln(64, "ccgutils.nim");
	inittypetables_469232();
	i_469300 = 0;
	nimln(1458, "system.nim");
	res_469302 = ((NU8) 0);
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_469302 <= ((NU8) 61))) goto LA1;
		nimln(1458, "system.nim");
		i_469300 = res_469302;
		nimln(66, "ccgutils.nim");
		asgnRefNoCycle((void**) &gcanonicaltypes_469228[(i_469300)- 0], NIM_NIL);
		nimln(1461, "system.nim");
		res_469302 = addInt(res_469302, 1);
	} LA1: ;
	popFrame();
}

static N_INLINE(NI, sonslen_192195)(ttype191847* n) {
	NI result;
	nimfr("sonsLen", "ast.nim")
	result = 0;
	nimln(1286, "ast.nim");
	{
		nimln(1286, "ast.nim");
		if (!(*n).Sons == 0) goto LA3;
		nimln(1286, "ast.nim");
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		nimln(1287, "ast.nim");
		nimln(1287, "ast.nim");
		result = (*n).Sons->Sup.len;
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(ttype191847*, lastson_192203)(ttype191847* n) {
	ttype191847* result;
	NI LOC1;
	NI TMP6199;
	nimfr("lastSon", "ast.nim")
	result = 0;
	nimln(1423, "ast.nim");
	nimln(1423, "ast.nim");
	nimln(1423, "ast.nim");
	LOC1 = 0;
	LOC1 = sonslen_192195(n);
	TMP6199 = subInt(LOC1, 1);
	if ((NU)((NI32)(TMP6199)) >= (NU)((*n).Sons->Sup.len)) raiseIndexError();
	result = (*n).Sons->data[(NI32)(TMP6199)];
	popFrame();
	return result;
}

N_NIMCALL(ttype191847*, getuniquetype_469401)(ttype191847* key) {
	ttype191847* result;
	NU8 k;
	nimfr("getUniqueType", "ccgutils.nim")
	result = 0;
	nimln(75, "ccgutils.nim");
	{
		nimln(75, "ccgutils.nim");
		if (!(key == NIM_NIL)) goto LA3;
		nimln(75, "ccgutils.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(76, "ccgutils.nim");
	k = (*key).Kind;
	nimln(77, "ccgutils.nim");
	switch (k) {
	case ((NU8) 1):
	case ((NU8) 2):
	case ((NU8) 31) ... ((NU8) 44):
	{
		nimln(82, "ccgutils.nim");
		result = key;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 6):
	case ((NU8) 7):
	case ((NU8) 26):
	case ((NU8) 28):
	case ((NU8) 29):
	case ((NU8) 0):
	case ((NU8) 45):
	{
		nimln(85, "ccgutils.nim");
		result = gcanonicaltypes_469228[(k)- 0];
		nimln(86, "ccgutils.nim");
		{
			nimln(86, "ccgutils.nim");
			if (!(result == NIM_NIL)) goto LA9;
			nimln(87, "ccgutils.nim");
			asgnRefNoCycle((void**) &gcanonicaltypes_469228[(k)- 0], key);
			nimln(88, "ccgutils.nim");
			result = key;
		}
		LA9: ;
	}
	break;
	case ((NU8) 8):
	case ((NU8) 51):
	case ((NU8) 12):
	case ((NU8) 60):
	case ((NU8) 61):
	case ((NU8) 54):
	case ((NU8) 52):
	case ((NU8) 53):
	case ((NU8) 55):
	case ((NU8) 56):
	case ((NU8) 57):
	case ((NU8) 58):
	{
		nimln(91, "ccgutils.nim");
		internalerror_168606(((NimStringDesc*) &TMP6198));
	}
	break;
	case ((NU8) 11):
	case ((NU8) 13):
	case ((NU8) 15):
	case ((NU8) 47):
	case ((NU8) 46):
	case ((NU8) 49):
	case ((NU8) 59):
	{
		ttype191847* LOC13;
		nimln(94, "ccgutils.nim");
		nimln(94, "ccgutils.nim");
		LOC13 = 0;
		LOC13 = lastson_192203(key);
		result = getuniquetype_469401(LOC13);
	}
	break;
	case ((NU8) 4):
	case ((NU8) 9):
	case ((NU8) 10):
	case ((NU8) 27):
	case ((NU8) 16):
	case ((NU8) 19):
	case ((NU8) 20):
	case ((NU8) 18):
	case ((NU8) 21):
	case ((NU8) 22):
	case ((NU8) 24):
	case ((NU8) 30):
	case ((NU8) 48):
	case ((NU8) 50):
	case ((NU8) 23):
	{
		NI h_469452;
		NI HEX3Atmp_469594;
		NI res_469596;
		nimln(105, "ccgutils.nim");
		{
			NIM_BOOL LOC17;
			nimln(105, "ccgutils.nim");
			LOC17 = 0;
			LOC17 = idtablehasobjectaskey_200154(gtypetable_469224[(k)- 0], &key->Sup);
			if (!LOC17) goto LA18;
			nimln(105, "ccgutils.nim");
			nimln(105, "ccgutils.nim");
			result = key;
			goto BeforeRet;
		}
		LA18: ;
		h_469452 = 0;
		HEX3Atmp_469594 = 0;
		nimln(106, "ccgutils.nim");
		nimln(106, "ccgutils.nim");
		HEX3Atmp_469594 = (gtypetable_469224[(k)- 0].Data->Sup.len-1);
		nimln(1451, "system.nim");
		res_469596 = 0;
		nimln(1452, "system.nim");
		while (1) {
			ttype191847* t;
			nimln(1452, "system.nim");
			if (!(res_469596 <= HEX3Atmp_469594)) goto LA20;
			nimln(1451, "system.nim");
			h_469452 = res_469596;
			nimln(107, "ccgutils.nim");
			if ((NU)(h_469452) >= (NU)(gtypetable_469224[(k)- 0].Data->Sup.len)) raiseIndexError();
			if (gtypetable_469224[(k)- 0].Data->data[h_469452].Key) chckObj((*gtypetable_469224[(k)- 0].Data->data[h_469452].Key).Sup.m_type, (&NTI191847));
			t = ((ttype191847*) (gtypetable_469224[(k)- 0].Data->data[h_469452].Key));
			nimln(108, "ccgutils.nim");
			{
				NIM_BOOL LOC23;
				nimln(108, "ccgutils.nim");
				LOC23 = 0;
				nimln(108, "ccgutils.nim");
				nimln(108, "ccgutils.nim");
				LOC23 = !((t == NIM_NIL));
				if (!(LOC23)) goto LA24;
				nimln(108, "ccgutils.nim");
				LOC23 = samebackendtype_234539(t, key);
				LA24: ;
				if (!LOC23) goto LA25;
				nimln(109, "ccgutils.nim");
				nimln(109, "ccgutils.nim");
				result = t;
				goto BeforeRet;
			}
			LA25: ;
			nimln(1454, "system.nim");
			res_469596 = addInt(res_469596, 1);
		} LA20: ;
		nimln(110, "ccgutils.nim");
		idtableput_200147(&gtypetable_469224[(k)- 0], &key->Sup, &key->Sup.Sup);
		nimln(111, "ccgutils.nim");
		result = key;
	}
	break;
	case ((NU8) 17):
	{
		nimln(113, "ccgutils.nim");
		{
			TNimObject* LOC32;
			nimln(113, "ccgutils.nim");
			nimln(113, "ccgutils.nim");
			if (!!((((*key).Flags &(1<<((((NU8) 8))&31)))!=0))) goto LA30;
			nimln(115, "ccgutils.nim");
			nimln(115, "ccgutils.nim");
			LOC32 = 0;
			LOC32 = idtableget_200137(gtypetable_469224[(k)- 0], &key->Sup);
			if (LOC32) chckObj((*LOC32).m_type, (&NTI191847));
			result = ((ttype191847*) (LOC32));
			nimln(116, "ccgutils.nim");
			{
				nimln(116, "ccgutils.nim");
				if (!(result == NIM_NIL)) goto LA35;
				nimln(117, "ccgutils.nim");
				idtableput_200147(&gtypetable_469224[(k)- 0], &key->Sup, &key->Sup.Sup);
				nimln(118, "ccgutils.nim");
				result = key;
			}
			LA35: ;
		}
		goto LA28;
		LA30: ;
		{
			NI h_469515;
			NI HEX3Atmp_469598;
			NI res_469600;
			nimln(121, "ccgutils.nim");
			{
				NIM_BOOL LOC40;
				nimln(121, "ccgutils.nim");
				LOC40 = 0;
				LOC40 = idtablehasobjectaskey_200154(gtypetable_469224[(k)- 0], &key->Sup);
				if (!LOC40) goto LA41;
				nimln(121, "ccgutils.nim");
				nimln(121, "ccgutils.nim");
				result = key;
				goto BeforeRet;
			}
			LA41: ;
			h_469515 = 0;
			HEX3Atmp_469598 = 0;
			nimln(122, "ccgutils.nim");
			nimln(122, "ccgutils.nim");
			HEX3Atmp_469598 = (gtypetable_469224[(k)- 0].Data->Sup.len-1);
			nimln(1451, "system.nim");
			res_469600 = 0;
			nimln(1452, "system.nim");
			while (1) {
				ttype191847* t;
				nimln(1452, "system.nim");
				if (!(res_469600 <= HEX3Atmp_469598)) goto LA43;
				nimln(1451, "system.nim");
				h_469515 = res_469600;
				nimln(123, "ccgutils.nim");
				if ((NU)(h_469515) >= (NU)(gtypetable_469224[(k)- 0].Data->Sup.len)) raiseIndexError();
				if (gtypetable_469224[(k)- 0].Data->data[h_469515].Key) chckObj((*gtypetable_469224[(k)- 0].Data->data[h_469515].Key).Sup.m_type, (&NTI191847));
				t = ((ttype191847*) (gtypetable_469224[(k)- 0].Data->data[h_469515].Key));
				nimln(124, "ccgutils.nim");
				{
					NIM_BOOL LOC46;
					nimln(124, "ccgutils.nim");
					LOC46 = 0;
					nimln(124, "ccgutils.nim");
					nimln(124, "ccgutils.nim");
					LOC46 = !((t == NIM_NIL));
					if (!(LOC46)) goto LA47;
					nimln(124, "ccgutils.nim");
					LOC46 = sametype_232139(t, key, 0);
					LA47: ;
					if (!LOC46) goto LA48;
					nimln(125, "ccgutils.nim");
					nimln(125, "ccgutils.nim");
					result = t;
					goto BeforeRet;
				}
				LA48: ;
				nimln(1454, "system.nim");
				res_469600 = addInt(res_469600, 1);
			} LA43: ;
			nimln(126, "ccgutils.nim");
			idtableput_200147(&gtypetable_469224[(k)- 0], &key->Sup, &key->Sup.Sup);
			nimln(127, "ccgutils.nim");
			result = key;
		}
		LA28: ;
	}
	break;
	case ((NU8) 14):
	{
		TNimObject* LOC51;
		nimln(129, "ccgutils.nim");
		nimln(129, "ccgutils.nim");
		LOC51 = 0;
		LOC51 = idtableget_200137(gtypetable_469224[(k)- 0], &key->Sup);
		if (LOC51) chckObj((*LOC51).m_type, (&NTI191847));
		result = ((ttype191847*) (LOC51));
		nimln(130, "ccgutils.nim");
		{
			nimln(130, "ccgutils.nim");
			if (!(result == NIM_NIL)) goto LA54;
			nimln(131, "ccgutils.nim");
			idtableput_200147(&gtypetable_469224[(k)- 0], &key->Sup, &key->Sup.Sup);
			nimln(132, "ccgutils.nim");
			result = key;
		}
		LA54: ;
	}
	break;
	case ((NU8) 25):
	{
		nimln(134, "ccgutils.nim");
		{
			nimln(134, "ccgutils.nim");
			nimln(134, "ccgutils.nim");
			if (!!(((*key).Callconv == ((NU8) 8)))) goto LA59;
			nimln(135, "ccgutils.nim");
			result = key;
		}
		goto LA57;
		LA59: ;
		{
			NI h_469574;
			NI HEX3Atmp_469602;
			NI res_469604;
			nimln(138, "ccgutils.nim");
			{
				NIM_BOOL LOC64;
				nimln(138, "ccgutils.nim");
				LOC64 = 0;
				LOC64 = idtablehasobjectaskey_200154(gtypetable_469224[(k)- 0], &key->Sup);
				if (!LOC64) goto LA65;
				nimln(138, "ccgutils.nim");
				nimln(138, "ccgutils.nim");
				result = key;
				goto BeforeRet;
			}
			LA65: ;
			h_469574 = 0;
			HEX3Atmp_469602 = 0;
			nimln(139, "ccgutils.nim");
			nimln(139, "ccgutils.nim");
			HEX3Atmp_469602 = (gtypetable_469224[(k)- 0].Data->Sup.len-1);
			nimln(1451, "system.nim");
			res_469604 = 0;
			nimln(1452, "system.nim");
			while (1) {
				ttype191847* t;
				nimln(1452, "system.nim");
				if (!(res_469604 <= HEX3Atmp_469602)) goto LA67;
				nimln(1451, "system.nim");
				h_469574 = res_469604;
				nimln(140, "ccgutils.nim");
				if ((NU)(h_469574) >= (NU)(gtypetable_469224[(k)- 0].Data->Sup.len)) raiseIndexError();
				if (gtypetable_469224[(k)- 0].Data->data[h_469574].Key) chckObj((*gtypetable_469224[(k)- 0].Data->data[h_469574].Key).Sup.m_type, (&NTI191847));
				t = ((ttype191847*) (gtypetable_469224[(k)- 0].Data->data[h_469574].Key));
				nimln(141, "ccgutils.nim");
				{
					NIM_BOOL LOC70;
					nimln(141, "ccgutils.nim");
					LOC70 = 0;
					nimln(141, "ccgutils.nim");
					nimln(141, "ccgutils.nim");
					LOC70 = !((t == NIM_NIL));
					if (!(LOC70)) goto LA71;
					nimln(141, "ccgutils.nim");
					LOC70 = samebackendtype_234539(t, key);
					LA71: ;
					if (!LOC70) goto LA72;
					nimln(142, "ccgutils.nim");
					nimln(142, "ccgutils.nim");
					result = t;
					goto BeforeRet;
				}
				LA72: ;
				nimln(1454, "system.nim");
				res_469604 = addInt(res_469604, 1);
			} LA67: ;
			nimln(143, "ccgutils.nim");
			idtableput_200147(&gtypetable_469224[(k)- 0], &key->Sup, &key->Sup.Sup);
			nimln(144, "ccgutils.nim");
			result = key;
		}
		LA57: ;
	}
	break;
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TNimObject*, tablegettype_469611)(tidtable191859 tab, ttype191847* key) {
	TNimObject* result;
	nimfr("tableGetType", "ccgutils.nim")
	result = 0;
	nimln(148, "ccgutils.nim");
	result = idtableget_200137(tab, &key->Sup);
	nimln(149, "ccgutils.nim");
	{
		NIM_BOOL LOC3;
		NI h_469646;
		NI HEX3Atmp_469665;
		NI res_469667;
		nimln(149, "ccgutils.nim");
		LOC3 = 0;
		nimln(149, "ccgutils.nim");
		LOC3 = (result == NIM_NIL);
		if (!(LOC3)) goto LA4;
		nimln(149, "ccgutils.nim");
		LOC3 = (0 < tab.Counter);
		LA4: ;
		if (!LOC3) goto LA5;
		h_469646 = 0;
		HEX3Atmp_469665 = 0;
		nimln(152, "ccgutils.nim");
		nimln(152, "ccgutils.nim");
		HEX3Atmp_469665 = (tab.Data->Sup.len-1);
		nimln(1451, "system.nim");
		res_469667 = 0;
		nimln(1452, "system.nim");
		while (1) {
			ttype191847* t;
			nimln(1452, "system.nim");
			if (!(res_469667 <= HEX3Atmp_469665)) goto LA7;
			nimln(1451, "system.nim");
			h_469646 = res_469667;
			nimln(153, "ccgutils.nim");
			if ((NU)(h_469646) >= (NU)(tab.Data->Sup.len)) raiseIndexError();
			if (tab.Data->data[h_469646].Key) chckObj((*tab.Data->data[h_469646].Key).Sup.m_type, (&NTI191847));
			t = ((ttype191847*) (tab.Data->data[h_469646].Key));
			nimln(154, "ccgutils.nim");
			{
				nimln(154, "ccgutils.nim");
				nimln(154, "ccgutils.nim");
				if (!!((t == NIM_NIL))) goto LA10;
				nimln(155, "ccgutils.nim");
				{
					NIM_BOOL LOC14;
					nimln(155, "ccgutils.nim");
					LOC14 = 0;
					LOC14 = sametype_232139(t, key, 0);
					if (!LOC14) goto LA15;
					nimln(156, "ccgutils.nim");
					nimln(156, "ccgutils.nim");
					if ((NU)(h_469646) >= (NU)(tab.Data->Sup.len)) raiseIndexError();
					result = tab.Data->data[h_469646].Val;
					goto BeforeRet;
				}
				LA15: ;
			}
			LA10: ;
			nimln(1454, "system.nim");
			res_469667 = addInt(res_469667, 1);
		} LA7: ;
	}
	LA5: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, makesinglelinecstring_469672)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_CHAR c_469676;
	NI i_469678;
	NI l_469680;
	nimfr("makeSingleLineCString", "ccgutils.nim")
	result = 0;
	nimln(159, "ccgutils.nim");
	result = copyString(((NimStringDesc*) &TMP6200));
	c_469676 = 0;
	nimln(2802, "system.nim");
	i_469678 = 0;
	nimln(2803, "system.nim");
	nimln(2803, "system.nim");
	l_469680 = s->Sup.len;
	nimln(2804, "system.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(2804, "system.nim");
		if (!(i_469678 < l_469680)) goto LA1;
		nimln(2805, "system.nim");
		if ((NU)(i_469678) > (NU)(s->Sup.len)) raiseIndexError();
		c_469676 = s->data[i_469678];
		nimln(161, "ccgutils.nim");
		nimln(161, "ccgutils.nim");
		LOC2 = 0;
		LOC2 = tocchar_166645(c_469676);
		result = resizeString(result, LOC2->Sup.len + 0);
appendString(result, LOC2);
		nimln(2806, "system.nim");
		i_469678 = addInt(i_469678, 1);
		nimln(2807, "system.nim");
		{
			nimln(2807, "system.nim");
			nimln(2807, "system.nim");
			nimln(2807, "system.nim");
			if (!!((s->Sup.len == l_469680))) goto LA5;
			nimln(2807, "system.nim");
			failedassertimpl_80421(((NimStringDesc*) &TMP6201));
		}
		LA5: ;
	} LA1: ;
	nimln(162, "ccgutils.nim");
	result = addChar(result, 34);
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, mangle_469684)(NimStringDesc* name) {
	NimStringDesc* result;
	NI i_469706;
	NI HEX3Atmp_469716;
	NI TMP6205;
	NI res_469718;
	nimfr("mangle", "ccgutils.nim")
	result = 0;
	nimln(165, "ccgutils.nim");
	result = copyString(((NimStringDesc*) &TMP6202));
	nimln(166, "ccgutils.nim");
	if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
	switch (((NU8)(name->data[0]))) {
	case 65 ... 90:
	case 97 ... 122:
	{
		NIM_CHAR LOC2;
		nimln(168, "ccgutils.nim");
		nimln(168, "ccgutils.nim");
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		LOC2 = 0;
		LOC2 = nsuToLowerChar(name->data[0]);
		result = addChar(result, LOC2);
	}
	break;
	case 48 ... 57:
	{
		NimStringDesc* LOC4;
		nimln(170, "ccgutils.nim");
		nimln(170, "ccgutils.nim");
		LOC4 = 0;
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		LOC4 = rawNewString(2);
appendString(LOC4, ((NimStringDesc*) &TMP6203));
appendChar(LOC4, name->data[0]);
		result = resizeString(result, LOC4->Sup.len + 0);
appendString(result, LOC4);
	}
	break;
	default:
	{
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(172, "ccgutils.nim");
		nimln(172, "ccgutils.nim");
		LOC6 = 0;
		nimln(172, "ccgutils.nim");
		nimln(172, "ccgutils.nim");
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		LOC7 = 0;
		LOC7 = nsuToHex(((NI64) (((NU8)(name->data[0])))), 2);
		LOC6 = rawNewString(LOC7->Sup.len + 3);
appendString(LOC6, ((NimStringDesc*) &TMP6204));
appendString(LOC6, LOC7);
		result = LOC6;
	}
	break;
	}
	i_469706 = 0;
	HEX3Atmp_469716 = 0;
	nimln(173, "ccgutils.nim");
	nimln(173, "ccgutils.nim");
	nimln(173, "ccgutils.nim");
	TMP6205 = subInt(name->Sup.len, 1);
	HEX3Atmp_469716 = (NI32)(TMP6205);
	nimln(1458, "system.nim");
	res_469718 = 1;
	nimln(1459, "system.nim");
	while (1) {
		NIM_CHAR c;
		nimln(1459, "system.nim");
		if (!(res_469718 <= HEX3Atmp_469716)) goto LA8;
		nimln(1458, "system.nim");
		i_469706 = res_469718;
		nimln(174, "ccgutils.nim");
		if ((NU)(i_469706) > (NU)(name->Sup.len)) raiseIndexError();
		c = name->data[i_469706];
		nimln(175, "ccgutils.nim");
		switch (((NU8)(c))) {
		case 65 ... 90:
		{
			NIM_CHAR LOC10;
			nimln(177, "ccgutils.nim");
			nimln(177, "ccgutils.nim");
			LOC10 = 0;
			LOC10 = nsuToLowerChar(c);
			result = addChar(result, LOC10);
		}
		break;
		case 95:
		{
		}
		break;
		case 97 ... 122:
		case 48 ... 57:
		{
			nimln(181, "ccgutils.nim");
			result = addChar(result, c);
		}
		break;
		default:
		{
			NimStringDesc* LOC14;
			NimStringDesc* LOC15;
			nimln(183, "ccgutils.nim");
			nimln(183, "ccgutils.nim");
			LOC14 = 0;
			nimln(183, "ccgutils.nim");
			nimln(183, "ccgutils.nim");
			LOC15 = 0;
			LOC15 = nsuToHex(((NI64) (((NU8)(c)))), 2);
			LOC14 = rawNewString(LOC15->Sup.len + 3);
appendString(LOC14, ((NimStringDesc*) &TMP6204));
appendString(LOC14, LOC15);
			result = resizeString(result, LOC14->Sup.len + 0);
appendString(result, LOC14);
		}
		break;
		}
		nimln(1461, "system.nim");
		res_469718 = addInt(res_469718, 1);
	} LA8: ;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI32)(a % b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(trope148007*, makellvmstring_469723)(NimStringDesc* s) {
	trope148007* result;
	NimStringDesc* res;
	NI i_469741;
	NI HEX3Atmp_469753;
	NI TMP6207;
	NI res_469755;
	trope148007* LOC10;
	nimfr("makeLLVMString", "ccgutils.nim")
	result = 0;
	nimln(187, "ccgutils.nim");
	result = NIM_NIL;
	nimln(188, "ccgutils.nim");
	res = copyString(((NimStringDesc*) &TMP6206));
	i_469741 = 0;
	HEX3Atmp_469753 = 0;
	nimln(189, "ccgutils.nim");
	nimln(189, "ccgutils.nim");
	nimln(189, "ccgutils.nim");
	TMP6207 = subInt(s->Sup.len, 1);
	HEX3Atmp_469753 = (NI32)(TMP6207);
	nimln(1451, "system.nim");
	res_469755 = 0;
	nimln(1452, "system.nim");
	while (1) {
		nimln(1452, "system.nim");
		if (!(res_469755 <= HEX3Atmp_469753)) goto LA1;
		nimln(1451, "system.nim");
		i_469741 = res_469755;
		nimln(190, "ccgutils.nim");
		{
			NI TMP6208;
			NI TMP6209;
			trope148007* LOC6;
			nimln(190, "ccgutils.nim");
			nimln(190, "ccgutils.nim");
			nimln(190, "ccgutils.nim");
			TMP6208 = addInt(i_469741, 1);
			TMP6209 = modInt((NI32)(TMP6208), 64);
			if (!(((NI) ((NI32)(TMP6209))) == 0)) goto LA4;
			nimln(191, "ccgutils.nim");
			nimln(191, "ccgutils.nim");
			LOC6 = 0;
			LOC6 = torope_148058(res);
			app_148040(&result, LOC6);
			nimln(192, "ccgutils.nim");
			res = setLengthStr(res, 0);
		}
		LA4: ;
		nimln(193, "ccgutils.nim");
		if ((NU)(i_469741) > (NU)(s->Sup.len)) raiseIndexError();
		switch (((NU8)(s->data[i_469741]))) {
		case 0 ... 31:
		case 128 ... 255:
		case 34:
		case 92:
		{
			NimStringDesc* LOC8;
			nimln(195, "ccgutils.nim");
			res = addChar(res, 92);
			nimln(196, "ccgutils.nim");
			nimln(196, "ccgutils.nim");
			nimln(196, "ccgutils.nim");
			if ((NU)(i_469741) > (NU)(s->Sup.len)) raiseIndexError();
			LOC8 = 0;
			LOC8 = nsuToHex(((NI64) (((NU8)(s->data[i_469741])))), 2);
			res = resizeString(res, LOC8->Sup.len + 0);
appendString(res, LOC8);
		}
		break;
		default:
		{
			nimln(197, "ccgutils.nim");
			if ((NU)(i_469741) > (NU)(s->Sup.len)) raiseIndexError();
			res = addChar(res, s->data[i_469741]);
		}
		break;
		}
		nimln(1454, "system.nim");
		res_469755 = addInt(res_469755, 1);
	} LA1: ;
	nimln(198, "ccgutils.nim");
	res = resizeString(res, 4);
appendString(res, ((NimStringDesc*) &TMP6210));
	nimln(199, "ccgutils.nim");
	nimln(199, "ccgutils.nim");
	LOC10 = 0;
	LOC10 = torope_148058(res);
	app_148040(&result, LOC10);
	popFrame();
	return result;
}
N_NOINLINE(void, ccgutilsInit)(void) {
	nimfr("ccgutils", "ccgutils.nim")
	nimln(201, "ccgutils.nim");
	inittypetables_469232();
	popFrame();
}

N_NOINLINE(void, ccgutilsDatInit)(void) {
}

